### ISSUE TITLE
Move articles to integrations 

### ISSUE THREAD

**Issue by laysauchoa** [aiven/devportal#1002]
articles in the monitoring section seems to be integrations between aiven and another technology. I'd suggest them to be organized in the integrations as datadog is right now. 

Also, move datadog article to there.

Find the articles here: https://developer.aiven.io/docs/platform/howto/list-monitoring.html

**Comment by laysauchoa** [comment]
fyi: @ftisiot

**Comment by lornajane** [comment]
But please don't move anything until we have #882  completed - this would break URLs.

**Comment by laysauchoa** [comment]
Hard to say if this should really be moved. I'm closing it for now.
