### ISSUE TITLE
Grafana plugins

### ISSUE THREAD

**Issue by laysauchoa** [aiven/devportal#1004]
Where grafana plugins list comes from? and how we have them up to date?

https://developer.aiven.io/docs/products/grafana/reference/plugins.html

**Comment by lornajane** [comment]
Tagging @FloorD since I think she has the best context but as I understand it, this information is not programmatically available.

**Comment by laysauchoa** [comment]
I figured out that currently, we are maintaining manually. This can be found in the private repository. Would it be nice to have a way to maintain this up-to-date with what is there and with one source of truth as well.

**Comment by laysauchoa** [comment]
This information is maintained manually. If at some point, we want to work in automating this then we can have a new ticket but it is not in our radar right now as we don't have a way to bring this info from private repo to the docs. Closing for now.
