### ISSUE TITLE
代理失败,电脑无法上网

### ISSUE THREAD

**Issue by guyuenaw12** [aiven/devportal#1020]
rejected  proxy/vmess/encoding: failed to read request header > websocket: close 1006 (abnormal closure): unexpected EOF

2022/06/21 05:12:57 **************:0 rejected  proxy/vmess/encoding: failed to read request header > websocket: close 1006 (abnormal closure): unexpected EOF
2022/06/21 05:13:17 **************:0 accepted tcp:clientservices.googleapis.com:443
2022/06/21 05:14:05 **************:0 accepted tcp:**************:443
2022/06/21 05:14:07 **************:0 rejected  proxy/vmess/encoding: failed to read request header > read tcp **************:443->**************:42344: i/o timeout
2022/06/21 05:14:28 **************:0 rejected  proxy/vmess/encoding: failed to read request header > websocket: close 1000 (normal)
2022/06/21 05:14:59 **************:0 rejected  proxy/vmess/encoding: failed to read request header > read tcp **************:443->**************:45002: i/o timeout
2022/06/21 05:15:14 **************:0 rejected  proxy/vmess/encoding: failed to read request header > websocket: close 1006 (abnormal closure): unexpected EOF
2022/06/21 05:15:26 **************:0 rejected  proxy/vmess/encoding: failed to read request header > websocket: close 1006 (abnormal closure): unexpected EOF

**Comment by laysauchoa** [comment]
which command did you try to run? this will make it easier to help you

**Comment by guyuenaw12** [comment]
> 您尝试运行哪个命令？这将使您更容易为您提供帮助

挂上节点后，打开谷歌日志就显示这个，  是基于 Vmess+WebSocket+TLS+CDN  搭建的节点， 突然不可翻墙. 但ping 服务器和域名都是通的

**Comment by laysauchoa** [comment]
@guyuenaw12: "After hanging up the node, open the Google log and it will show this. It is a node based on Vmess+WebSocket+TLS+CDN"

**Comment by lornajane** [comment]
This is not related to our project.
