### ISSUE TITLE
Migrate Manage Logging Level of Kafka Connect Cluster

### ISSUE THREAD

**Issue by ftisiot** [aiven/devportal#1033]
# What should we add to our content collections?

(more information is useful here! Were you trying to do something particular?)
Migrate 

https://help.aiven.io/en/articles/4945598-setting-the-logging-level-of-an-aiven-for-apache-kafka-connect-cluster

# Is this something you would work on yourself?

[X] I plan to open a pull request for this

**Comment by TibsAtWork** [comment]
Fixed by https://github.com/aiven/devportal/pull/1034
