### ISSUE TITLE
Linkcheck is failling on build

### ISSUE THREAD

**Issue by laysauchoa** [aiven/devportal#1041]
# What's wrong?

[Linkcheck](https://github.com/aiven/devportal/runs/7072859356?check_suite_focus=true) is failing due to Aiven console error and/or [API docs.](https://api.aiven.io/).

 
<img width="1786" alt="Screenshot 2022-06-27 at 13 31 16" src="https://user-images.githubusercontent.com/36624597/175945092-5c64774c-4394-41e9-8b5f-75b422811fd1.png">

**How to solve?** No actions needed from our side. For now, we can wait for this to be solved on the affected pages.

Thanks @ftisiot for reporting the issue.

**Comment by ftisiot** [comment]
Fixed https://status.aiven.io/incidents/rq0rx5syy0cq
