### ISSUE TITLE
Migrate article: Authentication tokens

### ISSUE THREAD

**Issue by lornajane** [aiven/devportal#1059]
Migrate the content from this article to fit the documentation portal format https://help.aiven.io/en/articles/2059201

(Assign this issue to yourself before you start, and remember to mention the issue number when you open your pull request)

**Comment by sluhur** [comment]
Looks like this link below is similar to the article above
https://developer.aiven.io/docs/platform/concepts/authentication-tokens.html

**Comment by ftisiot** [comment]
Exactly, closing this! Thanks for checking @sluhur
