### ISSUE TITLE
Migrate article: EOL for major versions of Aiven Services

### ISSUE THREAD

**Issue by lornajane** [aiven/devportal#1067]
Migrate the content from this article to fit the documentation portal format https://help.aiven.io/en/articles/4318172

(Assign this issue to yourself before you start, and remember to mention the issue number when you open your pull request)

**Comment by dragonlancewu** [comment]
PR: https://github.com/aiven/devportal/pull/1286

**Comment by harshini-rangaswamy** [comment]
Content migrated and available here - https://docs.aiven.io/docs/platform/reference/eol-for-major-versions.html#
