### ISSUE TITLE
Migrate article: COVID-19: Coronavirus update

### ISSUE THREAD

**Issue by lornajane** [aiven/devportal#1069]
Migrate the content from this article to fit the documentation portal format https://help.aiven.io/en/articles/3792926

(Assign this issue to yourself before you start, and remember to mention the issue number when you open your pull request)

**Comment by lornajane** [comment]
I think we have a few of these in the issues list, and I don't have a plan for them. I think it would be useful to add a tag and group them somehow so we can handle them all the same way when we decide.

**Comment by sluhur** [comment]
For now I put the link under Reference. Let me know if this is not the right place

**Comment by ftisiot** [comment]
This article shouldn't be moved since it's a one off reply valid last year but not needed anymore
