### ISSUE TITLE
Migrate article: Getting started with billing groups

### ISSUE THREAD

**Issue by lornajane** [aiven/devportal#1071]
Migrate the content from this article to fit the documentation portal format https://help.aiven.io/en/articles/4634847

(Assign this issue to yourself before you start, and remember to mention the issue number when you open your pull request)

**Comment by sluhur** [comment]
Looks similar to this
https://developer.aiven.io/docs/platform/concepts/billing-groups.html

**Comment by ftisiot** [comment]
I believe we're missing the part where you create a billing group, maybe we need a dedicated article
?

**Comment by staceysalamon-aiven** [comment]
I am working on making changes to some of the billing articles, so I'll pick this one up.
