### ISSUE TITLE
Migrate article: Viewing service logs

### ISSUE THREAD

**Issue by lornajane** [aiven/devportal#1072]
Migrate the content from this article to fit the documentation portal format https://help.aiven.io/en/articles/2357598

(Assign this issue to yourself before you start, and remember to mention the issue number when you open your pull request)

**Comment by sluhur** [comment]
@lornajane Where would be the best place to add the link for this in devportal?

**Comment by sluhur** [comment]
PR is here
https://github.com/aiven/devportal/pull/1205
