### ISSUE TITLE
Migrate article: Aiven Statement on L1TF Vulnerabilities

### ISSUE THREAD

**Issue by lornajane** [aiven/devportal#1077]
Migrate the content from this article to fit the documentation portal format https://help.aiven.io/en/articles/2241864

(Assign this issue to yourself before you start, and remember to mention the issue number when you open your pull request)

**Comment by sluhur** [comment]
@ftisiot Do we need to migrate this to devportal?

**Comment by ftisiot** [comment]
No need, thanks for checking
