### ISSUE TITLE
Migrate article: Technical Emails

### ISSUE THREAD

**Issue by lornajane** [aiven/devportal#1080]
Migrate the content from this article to fit the documentation portal format https://help.aiven.io/en/articles/5234705

(Assign this issue to yourself before you start, and remember to mention the issue number when you open your pull request)

**Comment by dragonlancewu** [comment]
PR: https://github.com/aiven/devportal/pull/1115

**Comment by runwuf** [comment]
done in https://github.com/aiven/devportal/pull/1115
https://developer.aiven.io/docs/platform/howto/technical-emails.html
