### ISSUE TITLE
Migrate article: Aiven Statement on Intel RIDL, Fallout and MDS Vulnerabilities

### ISSUE THREAD

**Issue by lornajane** [aiven/devportal#1085]
Migrate the content from this article to fit the documentation portal format https://help.aiven.io/en/articles/2984041

(Assign this issue to yourself before you start, and remember to mention the issue number when you open your pull request)

**Comment by harshini-rangaswamy** [comment]
@lornajane since the content of this article is better suited as a blog post, how should I process with this next?

**Comment by lornajane** [comment]
I don't think we should do anything, I'll close this.
