### ISSUE TITLE
aws: using Virtual Private Cloud (VPC) peering

### ISSUE THREAD

**Issue by laysauchoa** [aiven/devportal#1106]
Related to https://github.com/aiven/devportal/issues/796

**Comment by dewan-ahmed** [comment]
There's an upcoming change on the Aiven console related to VPC peering (specific to the target VPC peering information). This change is expected to go live by August 26th. I suggest we wait for this change to go in so that we can capture the up-to-date information in our docs.

**Comment by dewan-ahmed** [comment]
Hi @laysauchoa since I'm working on the GCP and Azure article, let me take this one as well as the work is similar. If it's Ok with you, I'll self-assign this task.

**Comment by dewan-ahmed** [comment]
This will be resolved via https://github.com/aiven/devportal/pull/1310

**Comment by laysauchoa** [comment]
Sure, @dewan-ahmed would be possible to add me as a reviewer? thank!

**Comment by dewan-ahmed** [comment]
Absolutely! Thank you.
