### ISSUE TITLE
EPIC: M3DB initial content

### ISSUE THREAD

**Issue by lornajane** [aiven/devportal#114]
- [x] M3 overview #77 
- [x] M3 getting started #86 
- [x] M3 connecting article #95 
- [x] M3 migrating article #104

**Comment by hab-anka** [comment]
Open questions: 
- what connect examples do we use?
- can we reuse the service setup from https://github.com/aiven/devportal/pull/140 for getting started?
- there seem to be no existing m3 migration info. How could we put it together?

**Comment by lornajane** [comment]
There are some code/connecting examples added (mostly taken from the aiven-examples repo)

I don't think we can re-use the service setup since the postgresql screenshots are a bit different and M3 has all the different connection types so it would be worth connecting things.

Migration information isn't something we already have (this is true for most of the projects) so one of us will need to create a sample project on InfluxDB (for example) and then migrate it to Aiven for M3 and document that process.
