### ISSUE TITLE
Restructure Kafka Connect connectors navigation

### ISSUE THREAD

**Issue by ftisiot** [aiven/devportal#1160]
# What should we add to our content collections?

(more information is useful here! Were you trying to do something particular?)

Source and sink connector navigation is, as of now, just a long list. It needs to be organised per source/target technology and cleaned a bit.

# Is this something you would work on yourself?

[X] I plan to open a pull request for this

**Comment by lornajane** [comment]
I think my questions are:
* do people come looking for Kafka + MongoDB, or are they looking for Kafka sinks?
* can we ask the marketing friends that worked on the website integration page whether we can use icons of products like Mongo, Snowflake, etc? And get those icons (we need this for the integrations pages as well, if you end up with more than just the connector images).
* are all the connectors now included?
* can you draw how you think about categorising them? Is there more than one option for how to do so?

The #1036 will open up some nicer options for these pages and we can also signpost them from more places.
