### ISSUE TITLE
Migrate Kafka Connect AWS IAM Assume Role credentials provider in Aiven S3 Sink Kafka Connector

### ISSUE THREAD

**Issue by ftisiot** [aiven/devportal#1168]
# What should we add to our content collections?

(more information is useful here! Were you trying to do something particular?)

Migrate https://help.aiven.io/en/articles/4983695-aws-iam-assume-role-credentials-provider-in-aiven-s3-sink-kafka-connector

# Is this something you would work on yourself?

[X] I plan to open a pull request for this

**Comment by lornajane** [comment]
Fixed in #1169
