### ISSUE TITLE
Add OpenSearch to the description here https://developer.aiven.io/docs/platform.html

### ISSUE THREAD

**Issue by ewe-gra** [aiven/devportal#1221]
# What should we add to our content collections?

In the description section here https://developer.aiven.io/docs/platform.html we are missing OpenSearch, beta features (unless we do not want the be there, like Flink). 

# Is this something you would work on yourself?

[ ] I plan to open a pull request for this

**Comment by laysauchoa** [comment]
I noticed ClickHouse is also missing
