### ISSUE TITLE
Add a GitHub Actions job to format embedded Terraform code within RST

### ISSUE THREAD

**Issue by dewan-ahmed** [aiven/devportal#1224]
# What's wrong?

Currently, formatting embedded Terraform code within RST files is a manual process. The proposal is to run a GitHub Actions job in the CI workflow that will automatically format any embedded Terraform code within RST files. Rather than having this job run with every PR, the job should run only if there’s any code change under https://github.com/aiven/devportal/tree/main/docs/tools/terraform

# Any other information

The RST support has been added to terrafmt via https://github.com/katbyte/terrafmt/pull/60

**Comment by laysauchoa** [comment]
seems like a good idea, I think I'll give a try for python code too 
https://github.com/aiven/devportal/issues/1226

**Comment by lornajane** [comment]
I would recommend we move the code out to terraform files and format those correctly, then include the code samples into the articles. The very early code snippets worked this way, but then we started just putting code inline. We've discussed this separation for making code examples more testable as well.

**Comment by dewan-ahmed** [comment]
When this issue was created, we didn't have the overall Terraform code testing conversation. I agree that rather than adding the formatting separately, the testing repo and associated GH action can take care of code formatting as well. Closing this issue as this work will be part of the broader Terraform code testing effort.
