### ISSUE TITLE
azure: using Virtual Private Cloud (VPC) peering

### ISSUE THREAD

**Issue by sebinsunny** [aiven/devportal#1231]
Use https://help.aiven.io/en/articles/3435096-azure-virtual-network-peering to migrate Azure VPC peering documentation to developer.aiven.io

Related to #796

**Comment by dewan-ahmed** [comment]
Hi @sebinsunny do you plan on working this migration content? Please reach out if you need any information on the process.

**Comment by dewan-ahmed** [comment]
This will be resolved via https://github.com/aiven/devportal/pull/1310

**Comment by laysauchoa** [comment]
Closing because it is resolved here: https://github.com/aiven/devportal/pull/1310
