### ISSUE TITLE
Vale is complaining about elasticsearch name in image path

### ISSUE THREAD

**Issue by ftisiot** [aiven/devportal#1235]
# What's wrong?

Vale is complaining about an image path containing `elasticsearch` but it shouldn't check path names

<img width="1308" alt="image showing two warnings related to image path containing the word elasticsearch" src="https://user-images.githubusercontent.com/11272743/184312475-f9662cf0-928f-4583-a10c-56507044c43a.png">

# URL of affected page, and any other information

**Comment by TibsAtWork** [comment]
When I run Vale 2.20.0 (the current version) on that file at the command line, I do not get any warnings.

However, if I run Vale 2.17.0, I do get the errors as shown. Foreshadowing: I also get them for 2.15.5

Our CI uses [vale-action](https://github.com/errata-ai/vale-action) to run vale. We specify
```
      uses: errata-ai/vale-action@master
```
to get the most recent version of vale-action.

The [vale-action Dockerfile](https://github.com/errata-ai/vale-action/blob/master/Dockerfile) specifies what version of vale to use:
```
FROM jdkato/vale:v2.15.5
```

It looks as if there are two things we might do to fix this:

1. Make an issue/PR for vale-action to update the version of vale.
2. Create a fork or vale-action that we can update ourselves.

(1) is a good idea, and such a request will probably be acted on fairly soon, but it doesn’t really solve the problem that we generally want the latest version of Vale, or at least a more recent one, and we don’t control vale-action’s updates.

(2) allows us to choose the version of Vale we want, but does require us to make sure that we don’t drift from the main vale-action

**Comment by TibsAtWork** [comment]
Turns out if we use the `reviewdog` branch of vale-action, which is now the default, then we get the latest branch of vale, and also the option to specify a particular branch. And that's now the official branch to use, according to https://github.com/marketplace/actions/vale-linter
See https://github.com/aiven/devportal/pull/1241

**Comment by TibsAtWork** [comment]
Note that this should also make work on https://github.com/aiven/devportal/issues/1130 easier.
