### ISSUE TITLE
The Vale workflow references "push" to `master` branch

### ISSUE THREAD

**Issue by TibsAtWork** [aiven/devportal#1237]
We use the workflow `.github/workflows/lint.yaml` to run Vale in CI

This contains
```
on:
  push:
    branches:
      - master
    tags:
      - '**'
  pull_request:
```
which I interpret to mean "run this action when pushing to `master` (any tags) or when creating a pull request"

The "run on PR" is what we're all used to. That's OK.

The "pushing to `master`" sounds to me like we should remove it:

* We no longer have a branch called `master`, it's called `main`, so this isn't triggered
* And we don't allow pushing directly to `main` anyway

Alternatively, to keep things extra safe, we could just replace `master` with `main` and then we're not relying on the "cannot push to master" rule elsewhere.

(Note: I'm not sure whether specifying `tags ['**']` is the same as not specifying `tags` at all, or whether it is indicating "`master` with a tag" - if we're keeping that, an explanatory comment and reference would be useful, as the docs at https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushbranchestagsbranches-ignoretags-ignore don't seem to mention this case)

**Comment by laysauchoa** [comment]
Tibs, I believe we should replace to ``main`` so we make sure if someone pushes to ``main`` that this workflow will run. Unless we are sure nobody has permission to push directly to ``main``. The tags are not so clear for me either. I thought this was a reference to the repository tags.

**Comment by TibsAtWork** [comment]
I think we should do *something*, but my initial read of the documentation for workflows didn't quite make it clear to me what is meant to happen if we change this to `main`. I'm fairly sure we disable pushing directly to `main`, but am not sure where that's done.

If no-one can push to `main`, at all, then this may be unnecessary "code".

**Comment by lornajane** [comment]
Yes, please replace with `main`. It's theoretically possible (for example, I have rights to do that) and I think it makes sense.
