### ISSUE TITLE
Maintenance task: update articles to show good coding practices

### ISSUE THREAD

**Issue by dewan-ahmed** [aiven/devportal#1253]
# What's wrong?

Aiven developer documentation should promote good coding practices. For example, some of the existing articles might contain hardcoded URI variables.

This is an ongoing task so that PRs can refer to this maintenance issue. 

Please don't close this issue. 

# URL of affected page, and any other information

- [ ] https://developer.aiven.io/docs/products/postgresql/howto/connect-python.html --> Update `python main.py` to something like `DATABASE_URL=<postgres_uri> python main.py` so that the URI is coming from an environment variable
- [ ] https://developer.aiven.io/docs/products/mysql/howto/connect-with-php.html --> Use getenv() function or .env files instead of `$uri = "MYSQL_URI";`

**Comment by lornajane** [comment]
Let's try to keep our issues to things that can be completed and closed. This long-running style is more like a regular chore, than an issue, so I'm closing this. Let's open issues with clear objectives when we spot something that can be improved.
