### ISSUE TITLE
Use internal links when linking to pages within the docs platform

### ISSUE THREAD

**Issue by lornajane** [aiven/devportal#1260]
# What's wrong?

We have links pointing to developer.aiven.io but these should all be internal links since they point to the same site (use the `:doc:` notation https://github.com/aiven/devportal#links) and we would want to stay on the same site even when working on a local or preview version of the platform.

I noticed it now because we're moving to docs.aiven.io and I see some links will end up in a redirect unnecessarily.

# URL of affected page, and any other information
One example is https://developer.aiven.io/docs/tools/terraform/reference/cookbook/grafana-m3db-postgresql-recipe but there are many others.

**Comment by TibsAtWork** [comment]
At the moment, problems with how Vale checks `:doc:` and `:ref:` mean that we can't always use them, and have to use a workaround.

I have got an issue raised with Vale on this - I'm hoping it will provide a solution (see https://github.com/errata-ai/vale/issues/470) as the Vale author thought the problem should not be happening.

Until then we'll sometimes have to use a traditional reStructuredText internal link to the full target URL.
Perhaps we could agree to put a comment before such workarounds - something like
```
.. Should be a :doc: link
```

**Comment by lornajane** [comment]
As an interim, we would need to update the developer.aiven.io links to be docs.aiven.io to avoid a clunky redirect experience

**Comment by TibsAtWork** [comment]
Update on use of `:doc:`:
* As the discussion at https://github.com/errata-ai/vale/issues/470 relates, it looks as if updating how we run Vale in CI (https://github.com/aiven/devportal/pull/1241) stops us from getting errors in the use of `:doc:`, where we were before.
* So it's probably safe to put the links we'd "undone" into standard `docutils` inline links back int `:doc:` links
* I've still got the original problems when I run `make spell` locally - but I'll investigate that separately

**Note** that all of the content of a `:doc:` item is ignored - so given```
:doc:`Is timeseries noticed here? <choosing-timeseries-database>`
```
we won't get an error for the `timeseries` in `Is timeseries noticed here?`.

**Comment by lornajane** [comment]
This is much improved, so I'll close this issue.
