### ISSUE TITLE
Fix Kafka Connect list-of-connector page to point to existing devportal articles

### ISSUE THREAD

**Issue by ftisiot** [aiven/devportal#1273]
# What's wrong?

(be specific, screenshots or a copy/paste of the affected part of the page is useful)
[Kafka Connect list-of-connector page](https://docs.aiven.io/docs/products/kafka/kafka-connect/concepts/list-of-connector-plugins.html) contains a lot of links to external repos/docs while the documentation has been written in devportal. We should therefore move to links to internal pages

# URL of affected page, and any other information

**Comment by bcrisologo** [comment]
I think some of the sink connectors can definitely be redirected to our current docs.  I'll take this one

**Comment by ftisiot** [comment]
Hi! There’s already a PR about this!

**Comment by ftisiot** [comment]
Sorry Blaise, we are addressing this as part of https://github.com/aiven/devportal/pull/1378 I believe we went straight to change mode without assigning the issue to us. Sorry for the duplicated work!
