### ISSUE TITLE
SEO: add a valid rel canonical

### ISSUE THREAD

**Issue by laysauchoa** [aiven/devportal#1278]
Checking [devportal](https://developer.aiven.io/) website with [Lighthouse tool](https://chrome.google.com/webstore/detail/lighthouse/blipmdconlkpinefehnmjammfjpmpbjk?hl=en), we have performed average (83/100) on SEO. To be considered good, we need to be above 90 points. 

These checks ensure that devportal page is following basic search engine optimization advice.

**Issue:**
Document does not have a valid rel=canonical. Multiple conflicting URLs (https://docs.aiven.io/index.html, https://developer.aiven.io/index). 

Read more: https://web.dev/canonical/?utm_source=lighthouse&utm_medium=devtools

**Comment by lornajane** [comment]
Can we get some advice on this one please? The preferred URL is https://docs.aiven.io (but it is a recent change, so I would expect the indexing tools to take a week or two to catch up) and I see a tag like `<link rel="canonical" href="[https://docs.aiven.io/docs/products/postgresql.html](view-source:https://docs.aiven.io/docs/products/postgresql.html)" />` on every page.  We have recently adjusted this on advice from @edithyeghiazaryan so it would be good to get more advice from her too on what else is needed.

**Comment by edithyeghiazaryan** [comment]
Hi Team,

The solution is **replacing the current canonical URLs with self-referencing canonical tags.** More details here - 

https://github.com/aiven/devportal/issues/934

Why are we again having the same issue solved a month ago? Besides the redirects, what other changes did we have?

**Comment by lornajane** [comment]
@edithyeghiazaryan This was introduced by a theme update last month, the theme originally did not have the canonical link so it was added to our custom template - the new theme version also has it (and it uses the site config so this is the better version to use). @angelinekwan has already send us a fix, I'll review.

**Comment by edithyeghiazaryan** [comment]
@lornajane  Thank you for the insights!
