### ISSUE TITLE
Migrate article: Missing PostgreSQL Datadog Metrics

### ISSUE THREAD

**Issue by lornajane** [aiven/devportal#1302]
Migrate the content from this article to fit the documentation portal format https://help.aiven.io/en/articles/5223432

(Assign this issue to yourself before you start, and remember to mention the issue number when you open your pull request)

**Comment by bcrisologo** [comment]
@lornajane where do you think this article would best fall under?

The ones I can find are putting that under:
- [Datadog and Aiven ](https://docs.aiven.io/docs/integrations/datadog.html)
- A new article under [PG > Reference](https://docs.aiven.io/docs/products/postgresql/reference.html)
- A new article under [PG > HowTo > Integrations](https://docs.aiven.io/docs/products/postgresql/howto/list-integrations.html)

Let me know your thoughts on where I can best place this article and I'll continue with it.

**Comment by lornajane** [comment]
I think it can go with the DataDog content, perhaps start a concept your article for the different service specific metrics that are available? I would also like it to be more like what is included rather than what is missing. Still accurate but using positive language ... Hopefully that makes sense!

**Comment by bcrisologo** [comment]
I'll have to scour through which metrics are available for our PG service in this case - so finding such metrics would take too long of a time if a table is included in the article.  Unless we could simply tailor the article to be "Postgres with Datadog is available" and be more positive, then add the "negative" as the last sub-section of the article?

**Comment by bcrisologo** [comment]
@lornajane Would pointing to the [General Metrics](https://docs.aiven.io/docs/products/postgresql/reference/pg-metrics.html#general-metrics) page be a good idea to start off the positive note for the paragraph?

I wasn't able to dissect the available metrics on a server/database level per-se, so pointing to the link may be the better way to go since we already have it outlined?

**Comment by bcrisologo** [comment]
@lornajane It seems the pull request #1402 was already created by someone else and we can merge this open issue with that one that the current assignee can work with? I haven't been able to progress on this so merging this with that new article may be better

**Comment by lornajane** [comment]
@harshini-rangaswamy  I'm assigning this over to you since I think you have a much clearer idea of what we do and don't have already in the docs in this area, and I'm hoping that you will be able to pick this up at some point. Unassign if that's not OK!

**Comment by harshini-rangaswamy** [comment]
> @harshini-rangaswamy I'm assigning this over to you since I think you have a much clearer idea of what we do and don't have already in the docs in this area, and I'm hoping that you will be able to pick this up at some point. Unassign if that's not OK!

Sure, thanks! I can take this up.

**Comment by lornajane** [comment]
Looks like #1402 covers what we needed here, so I'll close (@harshini-rangaswamy obvious re-open if you get to this and disagree!)
