### ISSUE TITLE
`avn service ca get` needs an additional parameter

### ISSUE THREAD

**Issue by lornajane** [aiven/devportal#1317]
# What should we add to our content collections?

We have docs for `avn service ca get` (see https://docs.aiven.io/docs/tools/cli/service.html#avn-service-ca-get) but the example command does not work as expected for a kafka service, since `ca` in this case is just a placeholder and it isn't clear what a valid value might be here. Dredging company slack history implies this could be Cassandra-only, please verify whether this is (still) the case and update the docs with a working example and any other information you think would help a user.

# Is this something you would work on yourself?

[ ] I plan to open a pull request for this

**Comment by reedwade** [comment]
Hi, yes, I even tripped over this today -- except it was failing for me for cassandra... is ref'd from https://docs.aiven.io/docs/products/cassandra/howto/connect-python.html

I cheated and downloaded the cert but will step back and see what's the deal here.
