### ISSUE TITLE
Retire help article without migration.

### ISSUE THREAD

**Issue by dewan-ahmed** [aiven/devportal#1320]
# What's wrong?

Please retire https://help.aiven.io/en/articles/4386696 which was originally written as an alternative to SAML IdP. Since SAML IdP feature is in place, the original help article can be retired.

# URL of affected page, and any other information

Original discussion is [here](https://github.com/aiven/devportal/issues/815).

**Comment by encima** [comment]
It might make sense to link to the standard SAML setup page as it talks about the IdP login there

**Comment by dewan-ahmed** [comment]
Would that be https://help.aiven.io/en/articles/4386696 pointing to https://docs.aiven.io/docs/platform/howto/list-saml.html?

If that's the case, I can add entries to the migration spreadsheet accordingly @lornajane .

**Comment by lornajane** [comment]
That would be helpful, thanks. Close this issue once no further actions are needed.

**Comment by dewan-ahmed** [comment]
Relevant entries added to the migration spreadsheet. Closing this issue.

**Comment by encima** [comment]
Yup. Thank you!

( https://www.facebook.com/aivencloud ) ( https://twitter.com/aiven_io ) ( https://www.linkedin.com/in/christopher-gwilliams-51322924/ )

Dr. Chris Gwilliams

Staff Solution Architect

Solution Architecture | Aiven

+358444915385

***@***.***

aiven.io ( http://aiven.io )

Helsinki, Finland
