### ISSUE TITLE
Create article: Setting up SAML authentication with Google Workspace

### ISSUE THREAD

**Issue by cr-aiven** [aiven/devportal#1324]
This was split off of the Migrate Google GSuite article. Workspace is different enough in appearance and in some setup that it needs it's own article. GSuite was deprecated in 2020 and now all signups for GSuite redirect to Workspace.
The original GSuite article can be used as a template.

**Comment by harshini-rangaswamy** [comment]
@lornajane 
Update from the TPM: Google Workspace is not fully supported yet. This functionality will most likely be available early next year.

**Comment by lornajane** [comment]
Thanks @harshini-rangaswamy, we should not create this documentation until the feature is complete and generally available

**Comment by harshini-rangaswamy** [comment]
> Thanks @harshini-rangaswamy, we should not create this documentation until the feature is complete and generally available

Would it be a good idea to set the priority to medium in this case?

**Comment by lornajane** [comment]
I would be tempted to close the issue and await new documentation coming when the feature is delivered, since this issue can't be completed at this time

**Comment by staceysalamon-aiven** [comment]
Hey @lornajane @harshini-rangaswamy, I am in the process of updating our SAML authentication setup article for changes related to an upcoming release and saw the links to the old help articles for G-Suite, Okta, Azure AD, etc. My feeling is that we should not document third party tools, but instead link to their docs, which I can do as part of this update. 

Is everyone fine with that approach?

Related issues: #807, #810, #811

**Comment by harshini-rangaswamy** [comment]
> Hey @lornajane @harshini-rangaswamy, I am in the process of updating our SAML authentication setup article for changes related to an upcoming release and saw the links to the old help articles for G-Suite, Okta, Azure AD, etc. My feeling is that we should not document third party tools, but instead link to their docs, which I can do as part of this update.
> 
> Is everyone fine with that approach?
> 
> Related issues: #807, #810, #811

I agree, linking them is good. That way, any changes to the third-party tool's documentation, we don't have to worry about it.

**Comment by lornajane** [comment]
I agree that we should not document third party or upstream tools again on our docs. However in this case, the documentation specifically shows how to use a third party _with Aiven_. The third party doesn't maintain the docs on creating a successful integration with our platform, and it's our users that need the information. So in this specific instance, it's not a case of linking to third party documentation, but of creating specific documentation on how to use a third party with Aiven. So we should probably maintain these documents. I'd be happy to have a middle section that has a very high level "create an account and get an access key from AwesomeThirdParty, using the (link to the docs)" or a similar approach that avoids us having a lot of screenshots and detailed information about what to type in each field - but I don't think we can just link to generic docs for the third parties in this instance.

**Comment by staceysalamon-aiven** [comment]
Thanks @lornajane. 

Yes, totally agree that we would not want to link to just like, the generic docs homepage. My idea was to find the relevant documentation (for example, https://support.google.com/a/answer/6087519?hl=en) and maybe note any important details (for example, our G Suite article has additional details about mapping that it could good to include). This way, we really only have to validate the link and some notes for this article instead of the exact details of where to find things in the G Suite UI, update screenshots when they change things, etc.

Let me know what you think!

**Comment by staceysalamon-aiven** [comment]
Update: The articles referenced above (apart from Google Workspace) have been migrated, so I will link to them from the main SAML article.

**Comment by lornajane** [comment]
@staceysalamon-aiven I still have this open issue for the Google Workspace, is this in progress somewhere? The old docs will be removed soon.

**Comment by staceysalamon-aiven** [comment]
Not that I am aware of, but I wasn't involved in those earlier discussions. @harshini-rangaswamy It looks like this was going to be closed until later?

**Comment by harshini-rangaswamy** [comment]
The last I heard was that this feature is not fully supported and is planned for early next year. Not sure if the priority has changed since then. @staceysalamon-aiven, you could check with Rick (TPM for this feature) if there has been any change and update/close this issue.

**Comment by lornajane** [comment]
Perfect! I feel fine about closing it, knowing that you are in touch with the product teams and will add the docs when the feature is out :) So I will let @staceysalamon-aiven check with Rick and then take the appropriate action
