### ISSUE TITLE
Update documentation related to external endpoints

### ISSUE THREAD

**Issue by aiven-tero** [aiven/devportal#1371]
# What's wrong?

In Aiven Console, the sidebar's menu item "Service Integrations" will be changed to "Integration Endpoints". Additionally, the page header is updated to "Integration Endpoints" and all of the integration help texts are going to be modified.

All existing documentation related to external endpoints should be updated to reflect the changes:
- [Datadog](https://help.aiven.io/services/getting-started-with-datadog)
- [AWS Cloudwatch Logs](https://help.aiven.io/en/articles/4134821-sending-service-logs-to-aws-cloudwatch)
- [AWS Cloudwatch Metrics](https://help.aiven.io/en/articles/5119409-aws-cloudwatch-metrics-integration)
- [External Elasticsearch](https://help.aiven.io/services/integrations/external-elasticsearch-log-integration)
- [Google Cloud Logging](https://help.aiven.io/en/articles/4209837-sending-service-logs-to-google-cloud-logging)
- [External Apache Kafka](https://docs.aiven.io/docs/products/kafka/kafka-mirrormaker/howto/integrate-external-kafka-cluster.html)
- [External PostgreSQL](https://docs.aiven.io/docs/products/clickhouse/howto/integrate-pg.html)
- [Jolokia](https://help.aiven.io/services/integrations/accessing-jmx-metrics-via-jolokia)
- [Prometheus](https://help.aiven.io/services/integrations/using-aiven-with-prometheus)
- [Syslog](https://help.aiven.io/services/integrations/remote-syslog-integration)

# URL of affected page, and any other information

Console link: https://console.aiven.io/project/dev-sandbox/service-integrations

**Comment by lornajane** [comment]
@aiven-tero This is great info! Could you please comment again on this issue once the change is live? I don't think we can update docs before that, particularly if we need to update screenshots in any of these articles.

**Comment by aiven-tero** [comment]
Hey @lornajane!

The changes have been merged to `main` branch [in this PR](https://github.com/aiven/aiven-core/pull/26191) and will be published to production in the next Console deployment, most likely sometime this week.

I will comment again once it is live.

**Comment by aiven-tero** [comment]
Changes now live: https://console.aiven.io/project/dev-sandbox/services

**Comment by lornajane** [comment]
@harshini-rangaswamy  or @staceysalamon-aiven is this already on your radar? I'm guessing it might be, in which case, here you go, there's already an issue open for this change.

I'm unclear how many screenshots will also be affected, if necessary we can open an issue to update those separately.

**Comment by harshini-rangaswamy** [comment]
> @harshini-rangaswamy or @staceysalamon-aiven is this already on your radar? I'm guessing it might be, in which case, here you go, there's already an issue open for this change.
> 
> I'm unclear how many screenshots will also be affected, if necessary we can open an issue to update those separately.

**Comment by harshini-rangaswamy** [comment]
> @harshini-rangaswamy or @staceysalamon-aiven is this already on your radar? I'm guessing it might be, in which case, here you go, there's already an issue open for this change.
> 
> I'm unclear how many screenshots will also be affected, if necessary we can open an issue to update those separately.
Yeah, this is on our radar! @staceysalamon-aiven, I know you are already working on the console-related changes. Happy to help here.

**Comment by staceysalamon-aiven** [comment]
I already had a PR for this. Didn't realize there was an issue, but have added it to the PR now. 👍  Thanks! @lornajane
