### ISSUE TITLE
Add OpenGraph metadata

### ISSUE THREAD

**Issue by lornajane** [aiven/devportal#139]
OpenGraph makes for richer links and shared content, add some opengraph tags, see https://ogp.me/

**Comment by lornajane** [comment]
Please let me know if you need any assets, copy, or anything else to be able to progress this task.

**Comment by aiven-hh** [comment]
This is only for the whole site like with sphinx-opengraph or do you need article/page specific meta tags?

**Comment by lornajane** [comment]
It looks like sphinxext-opengraph does page specific meta tags by default at least for the title and description (using the first few characters of the page, which would be fine for a starting point). We can use a single image for now though I think.
