### ISSUE TITLE
Create heading style for code-formatted content

### ISSUE THREAD

**Issue by lornajane** [aiven/devportal#141]
There are lots of places on the site (particularly in the CLI section) where we use code-formatted font in titles - sometimes that's the only thing in a title. The default formatted font is very grey and it makes the titles very hard to see. Could we please get some colour or font weight or something for these titles?

e.g.: https://developer.aiven.io/docs/tools/cli.html#billing-group

**Comment by lornajane** [comment]
I also notice that all of the code/literal styling produces a warning in the accessibility inspector

"Background and foreground colors do not have a sufficient contrast ratio."

**Comment by lornajane** [comment]
@turq84 is this something you'd be able to help with?

**Comment by turq84** [comment]
Yeah, I'll check it out. @lornajane

**Comment by lornajane** [comment]
Fixed in #209
