### ISSUE TITLE
Redirect doesn't work for pages without ".html" ending

### ISSUE THREAD

**Issue by byashimov** [aiven/devportal#1410]
# What's wrong?

Redirect doesn't work for pages without explicit html ending though that pages served by the web-server.

# URL of affected page, and any other information

This page has been moved to the terraform section, it has a redirect which doesn't work without html ending:  
https://docs.aiven.io/docs/products/opensearch/howto/upgrade-to-opensearch-with-terraform

It works this way:  
https://docs.aiven.io/docs/products/opensearch/howto/upgrade-to-opensearch-with-terraform.html

**Comment by harshini-rangaswamy** [comment]
Hi @byashimov - could you confirm if this issue still exists? I've checked the pages and didn't find the broken link.

**Comment by laysauchoa** [comment]
This is related to https://github.com/aiven/devportal/pull/1508

**Comment by lornajane** [comment]
@anelook is there any way we can abstract this into a rewrite rule? Your fix does work on the existing redirects and solves the immediate problem (thanks!) but will be very difficult to maintain correctly over time - I'm unclear what Sphinx is doing with the `.html` extension, which should never be used and makes us look very dated IMO!!
