### ISSUE TITLE
Create a howto document for source Kafka connect from RabbitMQ

### ISSUE THREAD

**Issue by jorgeuribe-aiven** [aiven/devportal#1416]
# What should we add to our content collections?

There is no Kafka connector that support [AMQP protocol ](https://www.rabbitmq.com/protocols.html)that is the core protocol supported by RabbitMQ, but a MQTT plugin can be enabled in RabbitMQ and this protocol can be used along with the MQTT source connector in Kafka connect.  

It would be useful to have a document where it shows how to configure the MQTT source connector. 

# Is this something you would work on yourself?

[ X] I plan to open a pull request for this

**Comment by ftisiot** [comment]
Amazing @jorgeuribe-aiven, please use one of our [connector existing docs](https://docs.aiven.io/docs/products/kafka/kafka-connect/howto/mongodb-poll-source-connector.html) as template
