### ISSUE TITLE
Update platform articles to reflect UI changes

### ISSUE THREAD

**Issue by staceysalamon-aiven** [aiven/devportal#1430]
# What's wrong?

The Aiven Console UI update will change where some features are found. Articles in the Billing, User/Access management, Service management, and SAML authentication sections will need to be updated.

Work is ongoing for this; I will update this issue when there is more info.

# Is this something you would work on yourself?

[X] I plan to open a pull request for this

**Comment by laysauchoa** [comment]
What do we need to change here? Images or names?

**Comment by staceysalamon-aiven** [comment]
@laysauchoa There's quite a bit changing. I am working on the relevant docs. :) I've assigned this to myself, but should have added in the description that I would handle this. I will do that now!

**Comment by laysauchoa** [comment]
Cool, thank you for clarifying it! :)
