### ISSUE TITLE
Search is returning 653 page(s) matching the search query "ex9jkCydLqo9rgUalygWgZhWhsPdq3" which is obviously wrong

### ISSUE THREAD

**Issue by lborda** [aiven/devportal#1441]
# What's wrong?
Search is returning 653 page(s) matching the search query "ex9jkCydLqo9rgUalygWgZhWhsPdq3" which is obviously wrong

# URL of affected page, and any other information

https://docs.aiven.io/search.html?q=ex9jkCydLqo9rgUalygWgZhWhsPdq3&check_keywords=yes&area=default

**Comment by lornajane** [comment]
Thanks, I noticed the other day that I had what seemed like an unlikely number of pages of results!! We'll take a look.
