### ISSUE TITLE
Add a "Sign up" button

### ISSUE THREAD

**Issue by lornajane** [aiven/devportal#148]
Add links to the main Aiven homepage, the console/signup page, and the support pages, maybe as a header in the template.

**Comment by gskhan** [comment]
https://www.figma.com/file/9mmKqatLFYFV8EYfWf2zHH/Developer-portal?node-id=0%3A1

**Comment by gskhan** [comment]
https://docs.github.com/en

**Comment by gskhan** [comment]
@turq84 can you please implement the version in the image? more data in the Figma file. Feel free to play with the bg color to make it blend better with the rest of the site.

This hast to be part of the template and has to be visible in all pages.

@lornajane will review this PR

Thank you.

![Top banner](https://user-images.githubusercontent.com/7808850/129264135-631e057e-b528-485f-abb4-c2b9e693cbcb.png)

**Comment by lornajane** [comment]
Fixed by #170  Thanks :)
