### ISSUE TITLE
Embedded videos on devportal

### ISSUE THREAD

**Issue by laysauchoa** [aiven/devportal#1488]
It makes sense to have some of the videos embedded so the user does not need to go to youtube in order to watch it. 

Check if there is an extension for that which we can use it. Just the key videos should be considered for this to not make the website noisy.

**Comment by lornajane** [comment]
This is an interesting idea but I'm not sure of the goal. The first step should be to propose some requirements for discussion before anything is implemented.

**Comment by laysauchoa** [comment]
Sure, this is an investigation ticket first.

**Comment by wojcik-dorota** [comment]
@lornajane @laysauchoa I support this idea. I can see quite a few screenshots in devportal how-tos. First thing is to limit their number, but if we go one step further, we can get rid of them by replacing a few images with one short mp4. This way the article would be quicker to update, shorter, and more attractive and approachable to the user. I even tried to include already some raw html video tag but it obviously didn't work. Is that possible to enable some video shortcode for devportal? I guess it would need some sphinx plug-in/configuration? Thank you for raining that issue :-)

**Comment by lornajane** [comment]
Let's put together some requirements and talk about the goals for this, we have a policy of not including video but we can revisit the decision factors and discuss this again, certainly! But let's discuss before investing more time in this, currently we should not be including video or animation content in our documentation.

**Comment by lornajane** [comment]
Let's put together some requirements and talk about the goals for this, we have a policy of not including video but we can revisit the decision factors and discuss this again, certainly! But let's discuss before investing more time in this, currently we should not be including video or animation content in our documentation.

**Comment by laysauchoa** [comment]
My conclusion is that is possible to include videos in devportal. You can check out an example in the flink page: https://docs.aiven.io/docs/products/flink/getting-started.html

**Comment by wojcik-dorota** [comment]
Yes, indeed, but you can only link to videos (YouTube, Vidyard, etc), you still cannot upload mp4 into the repo and use such a video file in your article.
