### ISSUE TITLE
Reordering and better title for Kafka Connect Source/sink HowTo

### ISSUE THREAD

**Issue by ftisiot** [aiven/devportal#1525]
# What can we help you with?

The current titles and ordering of kafka connect source/sink how to is quite disorganised in the navigation bar, should we aim to provide a better experience by shortening titles and putting them in alphabetical order

![current list of connector howto](https://user-images.githubusercontent.com/11272743/199930425-23fddb10-8bfd-4bcf-80c3-9d2e2d0cc0ee.png)

# Where would you expect to find this information?
in the main `_toc` file

**Comment by lornajane** [comment]
Could we also try to abbreviate what's in the nav? There's a lot of "create a ..... connector" which makes it harder to parse. I realise this might not work for all of them, but let's try.

**Comment by ftisiot** [comment]
Yep Agreed!
