### ISSUE TITLE
Rethink about Product ordering

### ISSUE THREAD

**Issue by ftisiot** [aiven/devportal#1597]
# What can we help you with?

The current product ordering in the left menu seems a bit random:

* Platform
* Integrations
* Aiven tools
* Apache Kafka
* PostgreSQL
* Apache Flink
* ClickHouse
* OpenSearch
* M3DB
* MySQL
* Redis
* Apache Cassandra
* Grafana

![Product ordering in the left menu](https://user-images.githubusercontent.com/11272743/203719321-b59c1a25-d2f5-448e-ad67-7b2df66eb065.png)

Should the product list follow some sort of priority or alphabetical order?

# Where would you expect to find this information?
Home page

**Comment by laysauchoa** [comment]
As a user, alphabetical is always easier to read (for me). I believe priority may differ from one person to another, and may change over time even for companies.

**Comment by lornajane** [comment]
This question I think is for you @harshini-rangaswamy - I think the current selection is an accurate reflection of "Aiven priority" order, but it's an easy thing to change if you can get feedback on what would make more sense.
