### ISSUE TITLE
Fix heading formatting on Migrate to virtual private cloud page

### ISSUE THREAD

**Issue by celestehorgan** [aiven/devportal#1663]
# What's wrong?

Headings on the [Migrate to a virtual private cloud](https://github.com/aiven/devportal/blob/main/docs/platform/howto/migrate-services-vpc.rst) Have a `#.` next to them.

# Remediation 

Remove the `#.` on these headings and use [Proper RST heading syntax](https://thomas-cokelaer.info/tutorials/sphinx/rest_syntax.html#headings) instead.

# URL of affected page, and any other information

https://docs.aiven.io/docs/platform/howto/migrate-services-vpc

**Comment by staceysalamon-aiven** [comment]
This was fixed in #1810.

**Comment by staceysalamon-aiven** [comment]
This was fixed in #1810.
