### ISSUE TITLE
Change the logo to PNG

### ISSUE THREAD

**Issue by hab-anka** [aiven/devportal#176]
# What's wrong?

There is a problem with the background of the image:
<img width="610" alt="devportal logo" src="https://user-images.githubusercontent.com/85879342/129704665-e1087bc6-194e-407e-a512-a27d14f7f7b5.png">
Can we change the logo to a PNG file with transparent background?

# URL of affected page, and any other information

Page header: https://developer.aiven.io/
<img width="563" alt="mobile devportal" src="https://user-images.githubusercontent.com/85879342/129690596-3c2f73fb-11c1-45e1-a265-715f14c173eb.png">

Can be replaced with the following resources provided by Evche:
[AD logo.zip](https://github.com/aiven/devportal/files/7000095/AD.logo.zip)

[AD DM logo.zip](https://github.com/aiven/devportal/files/7000098/AD.DM.logo.zip)

**Comment by lornajane** [comment]
Could you add an explanation of what the problem is, that changing the file type is the solution?

**Comment by lornajane** [comment]
New logos are being added to the project anyway.
