### ISSUE TITLE
Review how the GitHub ribbon displays on mobile version

### ISSUE THREAD

**Issue by hab-anka** [aiven/devportal#177]
# What's wrong?

The Fork me on Github blocks the title view. Can we either adjust this for mobile, or remove it from the mobile version

# URL of affected page, and any other information

All pages
<img width="563" alt="mobile devportal" src="https://user-images.githubusercontent.com/85879342/129690806-dbebda22-c6ef-4c9d-a43a-cf35471e21bf.png">

**Comment by lornajane** [comment]
Won'tFix
