### ISSUE TITLE
Add Getting started content for flink

### ISSUE THREAD

**Issue by ftisiot** [aiven/devportal#179]
# What should we add to our content collections?

We need to work on the Flink product documentation. Product is still in pre-beta but we can already create the general content like the main Index page (`docs/procucts/flink/getting-started.rst`). 

# Is this something you would work on yourself?

[X] I plan to open a pull request for this

**Comment by lornajane** [comment]
This exists https://developer.aiven.io/docs/products/flink/getting-started.html
