### ISSUE TITLE
Indexes

### ISSUE THREAD

**Issue by diawarr** [aiven/devportal#182]
Compile OpenSearch versions of the content in the following articles:
- http://help.aiven.io/en/articles/2541580-setting-the-index-retention-count-based-on-name-patterns
- http://help.aiven.io/en/articles/2413410-number-of-shards-and-indexes-in-elasticsearch
- http://help.aiven.io/en/articles/2342117-automatic-adjustment-of-elasticsearch-index-replication-factors

**Comment by lornajane** [comment]
Fixed by #183
