### ISSUE TITLE
Text links to wrong page

### ISSUE THREAD

**Issue by avnaprin** [aiven/devportal#1834]
# What's wrong?
in (https://aiven.io/postgresql) , under section "Build advanced applications with Aiven for PostgreSQL" , Resources "[What is PostgreSQL? (blog)] links to wrong page : (https://aiven.io/blog/an-introduction-to-m3)

**Comment by harshini-rangaswamy** [comment]
@avnaprin, the content on the Aiven website is managed by the marketing team. Could you please reach out to #ask-web-dx?

**Comment by harshini-rangaswamy** [comment]
Post this in the #ask-web-dx channel.
