### ISSUE TITLE
Migrate auth token information

### ISSUE THREAD

**Issue by lornajane** [aiven/devportal#189]
We have a basic howto on creating an auth token https://developer.aiven.io/docs/platform/howto/create_authentication_token.html

There's a help article with a bit more context to the different steps, let's use it to flesh out our howto https://help.aiven.io/en/articles/2059201-authentication-tokens

**Comment by lornajane** [comment]
Note that there isn't a redirect from the help article to the devportal howto yet, since one doesn't replace the other.

**Comment by dewan-ahmed** [comment]
Here's the change I have so far on my local branch:

1. A new file docs/platform/concepts/authentication-token.rst which is a reuse of [this help article](https://help.aiven.io/en/articles/2059201-authentication-tokens) with some additional intro text.
2. Few minor edits to docs/platform/howto/create_authentication_token.rst. This file references docs/platform/concepts/authentication-token.rst for concepts.
3. An entry to docs/platform/concepts.rst for adding the new file

I have the following mermaidjs diagram which is not rendering properly. Any tip on this is appreciated:
```
sequenceDiagram
    Client->>+Server: Here's my username/password. Give me a token.
    Server-->>-Client: Your username/password is valid. Here's a token. 
    Client->>+Server: Here's a token. Show me a list of my resources.
    Server-->>-Client: Your token is valid. Here's a list of your resources.  
```

I'm planning to raise a PR once I get some feedback on the above.

**Comment by lornajane** [comment]
Feel free to push a PR and mark it as Draft, it makes it easier for people to see, or to pull the branch locally to look at. Does the diagram render at all? I think it would help to see it.

**Comment by dewan-ahmed** [comment]
Fixed via https://github.com/aiven/devportal/pull/501
