### ISSUE TITLE
CLI docs for `avn service m3` command

### ISSUE THREAD

**Issue by ftisiot** [aiven/devportal#235]
# What should we add to our content collections?

Documenting the `avn service m3` that Aiven provides for Cassandra services

Please fork the [cli-avn-service branch](https://github.com/aiven/devportal/tree/cli-avn-service), have a look at the [integration page](https://github.com/aiven/devportal/blob/avn-service-integration/docs/tools/cli/service/integration.rst) for an example

# Is this something you would work on yourself?

[ ] I plan to open a pull request for this

**Comment by lornajane** [comment]
This is live https://developer.aiven.io/docs/tools/cli/service/m3.html
