### ISSUE TITLE
[PG] PostgreSQL Getting Started page improvements

### ISSUE THREAD

**Issue by lornajane** [aiven/devportal#29]
Let's flesh out this page a bit, a lot of users will come through here. My suggestions:
 
- Put the `psql` example on this page, so that people can immediately find it
- Add a sample database example such as [Pagila](https://github.com/devrimgunduz/pagila) as well, again to get people started
- End with links to some code examples, sample projects, or some other call to action to go to next

**Comment by ftisiot** [comment]
Pagila doesn't seem to work well with our `avnadmin` user. Many DDLs are failing for privilege related issues

**Comment by ftisiot** [comment]
Should this be closed?

**Comment by lornajane** [comment]
Close byt #38
