### ISSUE TITLE
Deploy test Debezium setup for Postgres and Kafka

### ISSUE THREAD

**Issue by lornajane** [aiven/devportal#296]
Migrate existing article https://help.aiven.io/en/articles/5278616-automated-debezium-kafka-postgresql-test-environment-deployment

**Comment by ftisiot** [comment]
I believe this is coming in the form of a recipe by @fmanimali!

**Comment by fmanimali** [comment]
indeedy!

**Comment by lornajane** [comment]
Did this get done? Where should we redirect the article to?

**Comment by fmanimali** [comment]
I have to catch up on this, can't remember where I was with this

**Comment by ftisiot** [comment]
It was solved with [PR #1110](https://github.com/aiven/devportal/pull/1110)

Recipe is https://docs.aiven.io/docs/tools/terraform/reference/cookbook/kafka-debezium-postgres-source.html

Redirect is already in place
