### ISSUE TITLE
PostgreSQL best practices checklist

### ISSUE THREAD

**Issue by lornajane** [aiven/devportal#298]
Let's replace this article https://help.aiven.io/en/articles/4738831-basic-postgresql-best-practices with more detailed information on HOW to do the things mentioned (link to them if they should be their own articles) and add any more tips that spring to mind. More than just a migration task.

**Comment by lornajane** [comment]
I don't agree that this should be closed. The original article linked here also had useful content about connection pooling and read-only replicas. We would need to bring that over before adding the redirect and marking this issue as closed (the content won't be accessible once the redirect is in place).

**Comment by ftisiot** [comment]
I believe the correct redirect for this one might be https://developer.aiven.io/docs/products/postgresql/howto/optimize-pg-slow-queries.html

**Comment by lornajane** [comment]
I think the connection pooling content is pretty much covered, but some of this read replica content would be good to bring. I'll PR this

**Comment by lornajane** [comment]
Closed in #896
