### ISSUE TITLE
PG Replication

### ISSUE THREAD

**Issue by lornajane** [aiven/devportal#33]
Let's inform users why they might like to replicate, how to set up replicas, and everything else they need to know.  Split the PR if it ends up bigger than 3 articles though!

Candidate content from the previous docs site:

* Replication
  - [x] High availability in Aiven for PostgreSQL 
  - [x] Setting up PostgreSQL logical replication
  - [x] Using PostgreSQL read-only replicas
  - [x] Aiven for PostgreSQL remote replica
  - [x] Detecting and addressing inactive or lagging PostgreSQL replication slots
  - Failover proxy

**Comment by ftisiot** [comment]
The failover proxy is partially covered in the `/concepts/upgrade-failover` article, I don't think this additional info is key for our developers

**Comment by lornajane** [comment]
Related content is now merged.
