### ISSUE TITLE
Update screenshot showing service create

### ISSUE THREAD

**Issue by lornajane** [aiven/devportal#369]
# What's wrong?

(be specific, screenshots or a copy/paste of the affected part of the page is useful)

The screenshot for creating a service is outdated because it shows the old summary section on the right hand side (it also shows elasticsearch rather than opensearch).

![Screenshot from 2021-11-24 17-13-19](https://user-images.githubusercontent.com/172607/143284910-228308a7-002e-4223-81c1-dc7d18f1bc24.png)

# URL of affected page, and any other information

URL: https://developer.aiven.io/docs/platform/howto/create_new_service.html

**Comment by dewan-ahmed** [comment]
https://github.com/aiven/devportal/pull/490 created as a fix.

**Comment by laysauchoa** [comment]
Fixed on #490
