### ISSUE TITLE
Clarify TLS information page

### ISSUE THREAD

**Issue by encima** [aiven/devportal#384]
# What's wrong?

The content of the [new page](https://developer.aiven.io/docs/platform/concepts/tls-ssl-certificates.html) feels like it is less informative than the [original](https://web.archive.org/web/20210415100958/https://help.aiven.io/en/articles/869463-ssl-tls-certificates)

# URL of affected page, and any other information

For non technical people, covering the difference between a self-signed cert and public (or linking to existing content). For technical people, a matrix of what services have what certs available could be useful.

Happy to make/propose some changes there as well.

**Comment by lornajane** [comment]
I'm closing because I'm not sure what changes we should make here, but very happy to get either more instructions, or a PR!
