### ISSUE TITLE
Migrating the Debezium Source connector

### ISSUE THREAD

**Issue by ftisiot** [aiven/devportal#466]
# What should we add to our content collections?

Migrating https://help.aiven.io/en/articles/3313065-using-debezium-connector-with-rds-postgresql-and-aiven-for-apache-kafka

# Is this something you would work on yourself?

[X] I plan to open a pull request for this

**Comment by laysauchoa** [comment]
Migration:
https://help.aiven.io/en/articles/3313065-using-debezium-connector-with-rds-postgresql-and-aiven-for-apache-kafka -> https://developer.aiven.io/docs/products/kafka/kafka-connect/howto/debezium-source-connector-pg.html
