### ISSUE TITLE
Discussion: add links to docs categories

### ISSUE THREAD

**Issue by FloorD** [aiven/devportal#471]
An idea I had is listing the articles that fall under a docs category to these blocks on the index pages for the different products.

Right now it looks like so:
![Screenshot (13)](https://user-images.githubusercontent.com/1087213/149191144-fc0cab37-f2ff-41b3-8d07-57c35b8ae01a.png)

And I experimented with it like so:
![Screenshot (15)](https://user-images.githubusercontent.com/1087213/149191165-106e7d12-25ae-46a8-8b3a-ceff8cd16287.png)

IDK, maybe it's at risk of getting too crowded, or y'all feel like the sidebar should provide ample navigation, but right now the blocks don't say very much unless you're familiar with the Diataxis framework...

**Comment by laysauchoa** [comment]
I agree. It would only fit if the number of articles is small but I believe they may just grown or be grouped in a new way, in the future.

**Comment by lornajane** [comment]
I definitely think that there's room to improve the navigation but we can't use this exact approach across other products like Kafka or Postgres - although those have subsections that we might want to surface and could help people to find their way.
