### ISSUE TITLE
Migrate "Using schema registry with Aiven for Apache Kafka" article

### ISSUE THREAD

**Issue by ftisiot** [aiven/devportal#475]
# What should we add to our content collections?

(more information is useful here! Were you trying to do something particular?)
The article [Using schema registry with Aiven for Apache Kafka](https://help.aiven.io/en/articles/2302613-using-schema-registry-with-aiven-for-apache-kafka) is one of the most read ones across our platform. 

The content is indeed interesting but I believe we can reshape it a bit to look like our "howtos" (example [here](https://developer.aiven.io/docs/products/kafka/howto/kcat.html) and [here for Java](https://developer.aiven.io/docs/products/postgresql/howto/connect-java.html)) 

I'm a bit rusty on Java, can someone help?

# Is this something you would work on yourself?

[ ] I plan to open a pull request for this

**Comment by TibsAtWork** [comment]
Migrated document is at https://developer.aiven.io/docs/products/kafka/howto/schema-registry.html
