### ISSUE TITLE
Migrate "Getting started with Aiven for Apache Kafka MirrorMaker 2" content

### ISSUE THREAD

**Issue by ftisiot** [aiven/devportal#476]
# What should we add to our content collections?

(more information is useful here! Were you trying to do something particular?)

https://help.aiven.io/en/articles/3992671-getting-started-with-aiven-for-apache-kafka-mirrormaker-2

# Is this something you would work on yourself?

[X] I plan to open a pull request for this

**Comment by TibsAtWork** [comment]
Now at https://developer.aiven.io/docs/products/kafka/kafka-mirrormaker/index.html
