### ISSUE TITLE
Take extra care with project names

### ISSUE THREAD

**Issue by lornajane** [aiven/devportal#484]
Many of the products on the Aiven platform are projects with proper trademarks and we need to name and handle those in line with each project's requirements.

In particular, the Apache projects should be referred to as "Apache [projectname]®" in the first occurence on each page to make sure that readers are clear that this is an upstream project. Later, we can use a shorter form such as just "Flink" or "Kafka".

- [ ] Automate checks to make sure that all project names are mentioned correctly, initially and then later, on every page
- [ ] Update any existing misuses of these project names, and check for display and layout issues where we make changes

**Comment by lornajane** [comment]
Vale can do something along these lines, looking at https://docs.errata.ai/vale/styles#conditional

**Comment by TibsAtWork** [comment]
Some significant amount of updating was done in https://github.com/aiven/devportal/pull/521

**Comment by dewan-ahmed** [comment]
There's a new update to Aiven for Redis and the usage of ™

An FYI to check the relevant internal channel.
