### ISSUE TITLE
Add a footer for disclaimers

### ISSUE THREAD

**Issue by lornajane** [aiven/devportal#485]
We need to add the following footer to every page on the site:

"Apache Kafka, Apache Kafka Connect, Apache Kafka MirrorMaker 2, Apache Flink and Apache Cassandra are either registered trademarks or trademarks of the Apache Software Foundation in the United States and/or other countries. M3, M3 Aggregator, OpenSearch, PostgreSQL, MySQL, Redis, InfluxDB, Grafana are trademarks and property of their respective owners. All product and service names used in this website are for identification purposes only and do not imply endorsement."

**Comment by lornajane** [comment]
I think we can just add it directly to the template, but we probably need to style it differently from normal text.

**Comment by TibsAtWork** [comment]
Note that the actual text to be included is still under review. See the internal slab page for the most current version.

**Comment by dewan-ahmed** [comment]
<img width="827" alt="Screen Shot 2022-02-07 at 12 36 35 PM" src="https://user-images.githubusercontent.com/30604461/152831246-dca82010-e601-418c-96eb-6ddf43706a55.png">

@lornajane @TibsAtWork WDYT? The disclaimer is added [here](https://github.com/aiven/devportal/blob/8d075a2dabc1d637bd45ab8b418cfb395f9c4250/_templates/page.html#L61) - emphasized and 2 size smaller fonts.

**Comment by TibsAtWork** [comment]
I like the italics, and the positioning. I think I'd perhaps only go down 1 font size - there's a balance between making it not too obtrusive, but letting it be obvious. But I'd want to see it at that size...
