### ISSUE TITLE
Developer setup instructions to ignore virtual environment folders via .gitignore are incorrect

### ISSUE THREAD

**Issue by robws** [aiven/devportal#522]
# What's wrong?

Instructions for [excluding virtual environment folders from the **devportal** repository](https://github.com/aiven/devportal#local-development) imply that naming the folder `env` or `virtualenv` will ensure it is excluded from `.gitignore`:

> If you call it something other than venv or env, make sure to add your preferred name to .gitignore.

However, the [current .gitignore file](https://github.com/aiven/devportal/blob/main/.gitignore) does not exclude these folders, as shown below.

# Steps to reproduce

1. Fork the [aiven devportal repo](https://github.com/aiven/devportal).
2. Clone the repo to a local folder.
3. Navigate to that folder in your console or command-line tool.
4. Create the virtual environment per the instructions, using the suggested `env` or `venv` convention:
`python3 -m venv env`
5. Check `git status` to confirm that there are no untracked files.
**Expected Result**
`git status` shows that there are no untracked files
**Actual Result**
`git status` shows `env/` folder as untracked. See below:
![2022-01-31 aivendev setup gitignore on forked repo](https://user-images.githubusercontent.com/29546533/151989167-35bacde6-cfa9-46fc-b0fe-f37a1c2f3cd8.png)

# Suggested fixes

## Option 1. (Preferred) Update [current .gitignore file](https://github.com/aiven/devportal/blob/main/.gitignore) 
Edit `.gitignore` exclude `/env` and `/venv` as the instructions indicate, making them correct as written.

## Option 2. Update [Developer setup instructions](https://github.com/aiven/devportal#local-development) to advise explicitly ignoring virtual environment files

**I would also suggest standardizing the virtual environment folder name in the repo folder to avoid polluting the `.gitignore` file with individual variations of that folder structure.**

# URL of affected page, and any other information

[Developer setup instructions](https://github.com/aiven/devportal#local-development)

**Comment by TibsAtWork** [comment]
Thank you for spotting this issue and fixing it.
