### ISSUE TITLE
Welcome new contributors

### ISSUE THREAD

**Issue by laysauchoa** [aiven/devportal#528]
# What can we help you with?

It would be nice for new contributors to be guided with their new PR maybe redirected to contributing guidelines automatically.
Some reference: https://medium.datadriveninvestor.com/welcome-first-time-contributors-to-your-github-repo-with-welcome-bot-93474758ac7e

# Where would you expect to find this information?
Once a new contributor opens a PR, for example

**Comment by lornajane** [comment]
Doesn't GitHub point to the contributing file automatically the first time that you open a pull request on a repo you haven't contributed to before?

**Comment by laysauchoa** [comment]
Sure! no, it is not automatic and feel free to close if does not fit this repo.

**Comment by lornajane** [comment]
Closing, I don't think we're doing this any time soon
