### ISSUE TITLE
Improve OpenSearch plan calculator image

### ISSUE THREAD

**Issue by laysauchoa** [aiven/devportal#554]
# What's wrong?
Improve the image by replacing for a table itself or high resolution image.

Page affected:
https://developer.aiven.io/docs/products/opensearch/concepts/indices.html#opensearch-plan-calculator

<img width="872" alt="Screenshot 2022-02-09 at 08 18 18" src="https://user-images.githubusercontent.com/36624597/153140858-f8c5c1ff-2f38-4241-a43b-ad097d4e65f5.png">

**Comment by lornajane** [comment]
We agreed when this PR was created that we would not embed items into the pages. A better image would be great though
