### ISSUE TITLE
Check product names

### ISSUE THREAD

**Issue by aposous** [aiven/devportal#56]
The old official product names ("Aiven Kafka" etc) were changed to the new ("Aiven for Apache Kafka") sometime in 2020. When transferring (or editing) content, check that product names follow the new format and the conventions as specified here: https://docs.google.com/document/d/1PklbdRuxSUycQ2vtSkYfdZZY7MokdR-sGkQYcZnzr-E/edit?usp=sharing
NOTE: M3 is the only product new enough to only have a new format name.

**Comment by lornajane** [comment]
Thanks @aposous are there any obvious misuses we should look out for? I can for example add "Aiven Kafka" to the reject word list, what else?

**Comment by lornajane** [comment]
We should also reject "Aiven for Kafka" - and I'm not sure we can do word rejects but we should be able to create Vale rules if not.
