### ISSUE TITLE
Replace image for higher quality one

### ISSUE THREAD

**Issue by laysauchoa** [aiven/devportal#579]
The image added to show the tag `preview` has low quality so I think it would be nice to replace for a higher quality one.
https://developer.aiven.io/docs/products/kafka/kafka-connect/concepts/list-of-connector-plugins.html

# URL of affected page, and any other information

**Comment by harshi1122** [comment]
![preview-kafka-connect-connectors](https://user-images.githubusercontent.com/87297355/154319044-c7c64793-9789-4fed-8027-3e2495abd661.png)

Here is the png file I secured 
If I were to increase the quality... where am I supposed to implement it? Do I just comment and attach the improved file here?

**Comment by laysauchoa** [comment]
<img width="617" alt="Screenshot 2022-03-02 at 17 39 08" src="https://user-images.githubusercontent.com/36624597/156406608-16a428ac-39e0-40b1-8006-51fcff5cbdfe.png">

**Comment by zoghlami-khalil** [comment]
Hey @laysauchoa 

I am new to Open source. I used the image you provided. Here is a preview: 
![Updated image](https://user-images.githubusercontent.com/76956031/168424935-aa61b07a-cf7b-4568-b8e3-52687b4ad4ea.JPG)

Can I add a PR?

**Comment by laysauchoa** [comment]
yes, please! @zoghlami-khalil

**Comment by laysauchoa** [comment]
This image is no longer there so this Issue can be closed.
