### ISSUE TITLE
PostgreSQL logical replication from GCP is possible

### ISSUE THREAD

**Issue by kevinbowman-aiven** [aiven/devportal#590]
# What's wrong?

On the following pages:
* https://developer.aiven.io/docs/products/postgresql/howto/setup-logical-replication.html
* https://developer.aiven.io/docs/products/postgresql/howto/migrate-aiven-db-migrate.html

there is an infobox at the top of the page that says "Google Cloud Platform’s PostgreSQL for CloudSQL does not currently support logical replication" (or similar).  This isn't true any more, GCP now supports the `pglogical` extension.  I've been able to setup logical replication from GCP -> Aiven using the first half of https://cloud.google.com/sql/docs/postgres/replication/configure-external-replica (up until "Configure the external replica") and then following the instructions on devportal's "Set up logical replication to Aiven for PostgreSQL" page.

There are a couple of gotchas (for which I have notes), and I haven't got aiven-db-migrate working yet, but I wanted to raise this issue so it was logged somewhere until I get a chance to write up the notes (or someone else gets there first...).

# URL of affected page, and any other information

https://developer.aiven.io/docs/products/postgresql/howto/setup-logical-replication.html
https://developer.aiven.io/docs/products/postgresql/howto/migrate-aiven-db-migrate.html

**Comment by ftisiot** [comment]
Fixed by #597

**Comment by kevinbowman-aiven** [comment]
Actually, a bit more investigation has happened, and I've been pointed at a different Google doc (thanks @ivanr-aiven and @runwuf !) and this is easier than I thought.  Ignore that GCP link I've put in the original issue, it totally leads down the wrong path, and look at https://cloud.google.com/sql/docs/postgres/replication/configure-logical-replication instead.  With that, our tooling and our managed migration service work just fine.  Apologies for the confusion!

**Comment by ftisiot** [comment]
Thanks Kevin! Should we close #590 then? Or should we add the link somewhere in the current doc before closing?

**Comment by kevinbowman-aiven** [comment]
Let's just close it, there's some blog posts in the pipeline which go through some real examples, and the change in #597 brings us back in line with reality.
