### ISSUE TITLE
OpenSearch: reestructure articles

### ISSUE THREAD

**Issue by laysauchoa** [aiven/devportal#591]
There are some contents that started to repeat themselves in terms of titles:

Connection articles:
- [ ] Python: https://developer.aiven.io/docs/products/opensearch/howto/connect-with-python.html
- [ ] NodeJS: https://developer.aiven.io/docs/products/opensearch/howto/connect-with-nodejs.html

Sample dataset: recipes
- [ ] Load the data with Python
- [ ] Load the data with NodeJS

Sample dataset: recipes

- [ ] Get data mapping with NodeJS
- [ ] https://github.com/aiven/devportal/pull/586

Following what @anelook said [here](https://github.com/aiven/devportal/pull/586):
With data mapping examples for both JS and Python the article grew. Let's move "Get data mapping" (with examples of JS and Python) to a separate article? 

Another way to organize those articles should be proposed to make the flow easier for the reader. Also, it would be nice to know what is your opinion in the `Sample dataset: recipes` article because from the title seems hard to know what it is about it.

But I understand it is linked in other places on the devportal.

**Comment by laysauchoa** [comment]
@anelook we can discuss here how it can be structured the OpenSearch files

**Comment by anelook** [comment]
My concern is that you cannot do what "Make queries with HTTP client" section says before you upload the data. So putting it as the first section will be confusing to the readers: they will have to scroll down, follow the steps and then scroll back up.  I think it is safe to put it at the end. It gives a generic example to play with data once it is loaded.

**Comment by anelook** [comment]
Regarding "Data mapping", it is a concept on its own, so I think it can be safely moved to a separate article, explaining what it is and giving examples how it can be done.
Initially, it was put here as another example what you can do once the data is loaded. However, by putting extra python code, it becomes heavy for one article.

**Comment by laysauchoa** [comment]
The current approach is right now a huge list of articles. I am bringing one example but the issue has more and we plan to bring more into those lists.

I would like that it is divided by category instead and the same approach has already been implemented for the Apache Kafka section before.

Check out here: https://github.com/aiven/devportal/pull/519

The reasons I feel the nested way is better:

- Titles are cleaner and more organized
- Avoid repetition of the same thing because we lack categories sections
- Can be hard to find without using the search tool (If not placed alphabetically)
- The emphasis in the title 

Possible disadvantage:

- search tools could work differently with categories and sub-categories kind of organization
- It could break the original link because we are changing the link
![current](https://user-images.githubusercontent.com/36624597/156323610-5dd4585b-4e14-46b2-b0c5-6615a737d170.png)
![proposal](https://user-images.githubusercontent.com/36624597/156323617-f74571ec-16bc-4f4a-86c6-6d5e8058660c.png)

**Comment by lornajane** [comment]
Kafka is divided into _groups_ of articles, covering similar topics and with 6-8 items in each subcategory, to avoid the navigation list getting very long. The approach proposed here of having one topic and then two sub articles is something quite different and I don't think it helps. We can re-organise the navigation without breaking links, and I think that using shorter article names for navigation titles could help here, without adding another layer of navigation between a user and the content they are looking for.
