### ISSUE TITLE
Linkcheck fails for a valid URL containing line selection

### ISSUE THREAD

**Issue by laysauchoa** [aiven/devportal#631]
I can access this URL but it shows like broken with the ``make linkcheck`` check.

Link: https://github.com/aiven/demo-opensearch-python/blob/main/index.py#L54-L72

<img width="812" alt="Screenshot 2022-03-11 at 12 02 17" src="https://user-images.githubusercontent.com/36624597/157855248-39414f94-b27c-4640-9b52-fc156e612ad2.png">

I noticed this on this PR: https://github.com/aiven/devportal/pull/604

Workaround is to not use the line selection option.

**Comment by laysauchoa** [comment]
I do not think this is urgent just a small thing that I noticed.

**Comment by lornajane** [comment]
The upstream Sphinx bug is here https://github.com/sphinx-doc/sphinx/issues/9435

**Comment by laysauchoa** [comment]
It does not see that any action is required from our side on this, so I am closing. Feel free to re-open if you need it.
