### ISSUE TITLE
Migrate End Of Support Schema Registry

### ISSUE THREAD

**Issue by ftisiot** [aiven/devportal#639]
# What should we add to our content collections?

(more information is useful here! Were you trying to do something particular?)

Migrate https://help.aiven.io/en/articles/5651983-end-of-support-for-confluent-schema-registry-on-aiven

# Is this something you would work on yourself?

[X] I plan to open a pull request for this

**Comment by lornajane** [comment]
Announcements were moved to the blog, closing.
