### ISSUE TITLE
Creating a PostgreSQL/MySQL read replica with Aiven Terraform provider

### ISSUE THREAD

**Issue by laysauchoa** [aiven/devportal#656]
https://help.aiven.io/en/articles/5721139-creating-a-postgresql-mysql-read-replica-with-aiven-terraform-provider

**Comment by laysauchoa** [comment]
Maybe this should go to Terraform session, wdyt @dewan-ahmed?

**Comment by dewan-ahmed** [comment]
Hi @laysauchoa I have [a similar article](https://help.aiven.io/en/articles/5372422-terraform-to-apply-promote-to-master-on-postgresql-mysql-replica) as part of [this Epic](https://github.com/aiven/devportal/issues/711). I wonder if I can merge two articles into one migrated Terraform recipe. Looking for some PG/MySQL expertise here.

**Comment by laysauchoa** [comment]
Hey, yes! I will sign to terraform then cause I think it makes sense.

**Comment by laysauchoa** [comment]
Closed as it is replicated and no longer from mysql but from terraform topics.

**Comment by dewan-ahmed** [comment]
Thanks @laysauchoa 

https://github.com/aiven/devportal/issues/1035 is the issue to track the future work.
