### ISSUE TITLE
Document: How to enable Aiven password

### ISSUE THREAD

**Issue by laysauchoa** [aiven/devportal#677]
Trying to login with this without having a Aiven password does not work

```
avn user login <user@aiven.io>
```

This is the error message:

```
❯ avn user login [user-email]()
[user-emal]()'s Aiven password:
ERROR	command failed: Error: {"errors":[{"message":"Authentication failed","status":403}],"message":"Authentication failed"}
```
I believe this documentation is missing in dev portal. I was referring to this [blog](https://aiven.io/blog/command-line-magic-with-the-aiven-cli).

Here are some steps that needs to be taken to make it work:

- Enable Aiven password

<img width="1207" alt="Screenshot 2022-03-24 at 13 42 25" src="https://user-images.githubusercontent.com/36624597/159920868-11639a6a-7fbe-4093-bdb4-5da4fadf047b.png">

- Check if password works properly in the login

<img width="1207" alt="Screenshot 2022-03-24 at 13 44 15" src="https://user-images.githubusercontent.com/36624597/159920886-72057b81-3490-4e6e-a374-3f956b6fa6f1.png">

As suggestion from @ftisiot this article should be in: **How to create a Aiven Password** and linked to **How to login with Aiven CLI**.

**Comment by laysauchoa** [comment]
Motivation had changed a bit: This is needed if the user wants to authenticate and log in directly without using any 3rd parties by using Aiven username and password.

Still blog should be fixed to follow the token access instead of Aiven password access.

**Comment by TibsAtWork** [comment]
The CLI blog post is due to be replaced by a new one.
