### ISSUE TITLE
[EPIC] Document ALL Kafka Connect Connectors

### ISSUE THREAD

**Issue by ftisiot** [aiven/devportal#685]
Link of available connectors as of 29/03/2022, please group into issues, and track within this issue description

- Couchbase Sink
- Couchbase Source
- Stream Reactor Cassandra Sink #1156
- Stream Reactor Cassandra Source #1156
- Stream Reactor InfluxDB Sink
- Stream Reactor MongoDB Sink #846
- Stream Reactor MQTT Sink
- Stream Reactor MQTT Source
- Stream Reactor Redis Sink #858
- Google Cloud Pub/Sub Sink
- Google Cloud Pub/Sub Source
- Google Cloud Pub/Sub Lite Sink
- Google Cloud Pub/Sub Lite Source
- MongoDB Kafka Sink Connector #845
- MongoDB Kafka Source Connector #849
- Snowflake Sink #700
- Splunk Sink
- Google BigQuery Sink #691
- Elasticsearch sink #566
- JDBC Sink #600
- JDBC Source #422
- Google Cloud Storage sink #633
- HTTP sink #708
- Opensearch sink #566
- Aiven - Amazon AWS S3 sink #498
- Confluent - Amazon AWS S3 sink #561
- Schema Source
- Debezium - MongoDB #837
- Debezium - MySQL #791
- Debezium - PostgreSQL #466
- Debezium - SQL Server #834

# Working Issues

- [X] #466
- [X] #498
- [X] #561
- [X] #600
- [X] #422
- [X] #566
- [X] #633
- [x] #691
- [x] #700
- [x] #708
- [x] #791
- [x] #834
- [x] #837
- [x] #845
- [x] #846
- [x] #849
- [x] #858

**Comment by lornajane** [comment]
Completed :)
