### ISSUE TITLE
'Page Not Found' for a Terraform-related page that is showing up in Google search

### ISSUE THREAD

**Issue by dewan-ahmed** [aiven/devportal#689]
# What's wrong?

1. Google "aiven terraform change plan"
2. This is the search result.
<img width="901" alt="Screen Shot 2022-03-31 at 10 44 43 AM" src="https://user-images.githubusercontent.com/30604461/161070008-b80a70ae-2314-4940-8789-1198b3a8d5df.png">

3. Clicking the link results in:
 
<img width="1064" alt="Screen Shot 2022-03-31 at 10 44 11 AM" src="https://user-images.githubusercontent.com/30604461/161070174-f06b366f-bc78-4822-a26d-98a044ac7d47.png">

# URL of affected page, and any other information

The link changed from https://developer.aiven.io/docs/tools/terraform/upgrade-provider-v1-v2 to https://developer.aiven.io/docs/tools/terraform/howto/upgrade-provider-v1-v2.html based on restructuring folder
via [this PR](https://github.com/aiven/devportal/pull/646)

However, this is not a migration work (i.e. the previous document existed on DevPortal already).

Is Google storing the old link in cache?

**Comment by anelook** [comment]
Some quick googling shows these options:
- we keep it as it is and it will take some time (30-60 days) for Google to give up on those pages
- to speed up process we change error to 410 to indicate that it is a not temp 404 situation (not clear to me yet how this can be achieved)
- we can consider adding robots.txt to have granular control on what is indexed. However, this means additional maintenance step


Do we have someone who has knowledge on these topics? If not - I can dive deeper and look at what option is better alternative for our case.

**Comment by dewan-ahmed** [comment]
Thanks for these additional info @anelook 

In case we don't have experts on the topics you mentioned, I'll be interested to learn these alongside.

Copying @lornajane for her thoughts.

**Comment by lornajane** [comment]
We left it and the index should catch up
