### ISSUE TITLE
Improve the getting started guide for Aiven for Redis

### ISSUE THREAD

**Issue by dewan-ahmed** [aiven/devportal#698]
# What should we add to our content collections?

[Postgres getting started guide](https://developer.aiven.io/docs/products/postgresql/getting-started.html) actually guides the user through service creation. 

When I read the [Aiven for Redis getting started guide](https://developer.aiven.io/docs/products/redis/get-started.html), it seems that the guide assumes that the user has already created a Redis service

> Once the service creation is initiated...

Some basic instructions on choosing a cloud provider, plan, etc might help the reader since this is the very first place they're sent to when trying to create an Aiven for Redis instance.

# Is this something you would work on yourself?

As a #good-first-issue, I'll leave it open for anyone to grab. The suggested change is:

1. Observe the [Postgres getting started guide](https://developer.aiven.io/docs/products/postgresql/getting-started.html) or [Flink getting started guide](https://developer.aiven.io/docs/products/flink/getting-started.html)
2. Use that as a reference to improve [Aiven for Redis getting started guide](https://developer.aiven.io/docs/products/redis/get-started.html) that *guides* the user step-by-step to service creation.
3. Once you're happy, create a PR and improve based on feedback.

**Comment by pparmin** [comment]
Hey :)

I have started working on this. I have already implemented a help section for creating a Redis service, very similar to the [Flink getting started guide](https://developer.aiven.io/docs/products/flink/getting-started.html). I think it would be great to have a similar section which gives an example for how this could be done using the [Aiven CLI](https://github.com/aiven/aiven-client). Once done, I will open a Feature Request. 

If you have any comments, please let me know.

**Comment by dewan-ahmed** [comment]
Excellent. Thanks @pparmin ; looking forward to your pull request.

**Comment by laysauchoa** [comment]
I was thinking that maybe is a good idea to reuse the content about how to create a service. For example, how it is done here:

https://developer.aiven.io/docs/products/clickhouse/getting-started.html

I'd suggest that we just redirect the user to the general way of creating a service rather than explaining it again. My main reasons are:
- reuse content
- avoid to get outdated fast

Do you think would be better to have the same steps again @dewan-ahmed and why? 

Another option could be to have some automatic way to copy those steps around the getting started service page, for example.

**Comment by dewan-ahmed** [comment]
Hi @laysauchoa, this issue was created to match the same practice on Redis getting started page since a number of other getting started pages exist - [PG getting started](https://developer.aiven.io/docs/products/postgresql/getting-started.html),[Kafka getting started](https://developer.aiven.io/docs/products/kafka/getting-started.html), [MySQL getting started](https://developer.aiven.io/docs/products/mysql/get-started.html) with details on how to create the service.

However,  using a common getting started content seems better from the reusability POV and since we already have a [generic service creation page](https://developer.aiven.io/docs/platform/howto/create_new_service.html), it makes sense to reuse that one.

Few points:

1. If we want to keep consistency in our docs, all the other product pages should follow the same model as the clickhouse getting started page.
2. How do we balance ease of maintenance and user convenience? For ease of maintenance, the generic service creation page should have little to no product specific instructions. For example, "For Aiven for Apache Kafka®, Aiven for PostgreSQL®, and Aiven for MySQL services, you can also select Add disk storage to configure additional storage on top of the amount defined in your selected service plan." However, with little maintenance overhead, these lines help the reader understand specific product service creation.

Thanks for raising a valid point. I agree with reusing the same service creation page as the clickhouse docs.

@pparmin what's your thought?

**Comment by pparmin** [comment]
Hey @laysauchoa & @dewan-ahmed, 

I completely agree with the points raised by the both of you. I believe in long-term maintainability, especially in a scenario where changes to the product may happen in the future. It would effectively make it harder for us to keep an eye on all getting started guides and keep them aligned. 

> How do we balance ease of maintenance and user convenience? 
Maybe we can introduce a note on the products that have extra options? However, this would once again lead to a scenario where we would have to maintain the notes for each page. We could also add some special notes for specific services on the general page, but that would mean we have to mention certain products there. I do think it's the better option in terms of user convenience though.
