### ISSUE TITLE
Should we publish our "meta" documentation?

### ISSUE THREAD

**Issue by TibsAtWork** [aiven/devportal#713]
Our README, CONTRIUTING file, etc., are written in reStructuredText, but we don't actually publish them to https://developer.aiven.io/

This also means they don't get included in `make html` and `make spell`, for instance.

https://github.com/aiven/devportal/pull/510 will also introduce a README for how we use `vale` to lint our documentation, and that also is not published to https://developer.aiven.io/

Sphinx would allow us to create a separate area of the devportal documentation gathering together such things (the published layout does not necessarily need to reflect the actual layout of files).

*Do we want to do this?*

**Comment by lornajane** [comment]
I think the files are better off in the repository as they are now (and I can't imagine us prioritising this). Closing.
