### ISSUE TITLE
Fix year in the footer

### ISSUE THREAD

**Issue by laysauchoa** [aiven/devportal#780]
On the https://developer.aiven.io/ we have “Copyright © 2021, Aiven Team” in the footer -> Could be updated to 2022

**Comment by laysauchoa** [comment]
yes, go ahead @siddharth-kaushik

**Comment by zoghlami-khalil** [comment]
@siddharth-kaushik  Are you still working on this? I believe I found a fix for it

**Comment by siddharth-kaushik** [comment]
Sure. Please go ahead 👍

**Comment by zoghlami-khalil** [comment]
Thanks @siddharth-kaushik :heart:

@laysauchoa can you please take a look at it?
