### ISSUE TITLE
Make search work in local dev environments

### ISSUE THREAD

**Issue by kevinbowman-aiven** [aiven/devportal#781]
It would be good to have the full search experience (HTML-rendered results page) in a local dev environment.  Currently, the netlify function runs locally but we need to see the results in JSON format.

The problem is that `netlify dev` runs a server on a different port (and therefore different origin) than `make livehtml` but there's no cross-origin support by default.

**Comment by kevinbowman-aiven** [comment]
I have started a branch with the changes needed to make search render locally, but it is not currently in a state to PR as it *only* works in dev and will break production.  However, it shows what changes are needed; the next step is to make some kind of switch to make it use a different config or endpoint in dev as it does in production.

The branch is https://github.com/aiven/devportal/tree/local-search-in-dev

**Comment by kevinbowman-aiven** [comment]
An alternative would be to have the `netlify` tool serve the whole site from a single origin, instead of using the sphinx server.

**Comment by lornajane** [comment]
This will come with the move to Cloudflare
