### ISSUE TITLE
Migrate Ruby examples for connecting to Apache Kafka

### ISSUE THREAD

**Issue by TibsAtWork** [aiven/devportal#786]
Migrate article about connecting to and using Kafka with Ruby

https://help.aiven.io/en/articles/5344094-ruby-examples-for-testing-aiven-for-apache-kafka

- [ ]  I plan to open a pull request for  this

**Comment by harshini-rangaswamy** [comment]
hi @TibsAtWork 
As per your note on this [spreadsheet](https://docs.google.com/spreadsheets/d/1zTIAHTyETfj4zVG9HASWT3l2zQYk7uydjftUB4LF2Kc/edit#gid=413497694), you mentioned  - We don't have Ruby examples for anything else, and the version of Ruby mentioned is from 2015, so this may be quite old code. 
Can we close this issue?

**Comment by TibsAtWork** [comment]
Yes, I think so - I think the right thing to do is to look at Ruby examples as a whole later on.
I shall close this, thanks.
