### ISSUE TITLE
Migrating and verifying InfluxDB articles

### ISSUE THREAD

**Issue by FloorD** [aiven/devportal#788]
InfluxDB articles from Help. 

~[ ] [InfluxDB Series Cardinality](https://help.aiven.io/en/articles/1640634-influxdb-series-cardinality)~ _The issue was resolved, Mika confirmed this article can be archived_
[ ] [InfluxDB Retention Policies](https://help.aiven.io/en/articles/893576-influxdb-retention-policies)
[ ] [Getting started with Aiven for InfluxDB](https://help.aiven.io/en/articles/745911-available-influxdb-commands)
[ ] [Available InfluxDB commands](https://help.aiven.io/en/articles/745911-available-influxdb-commands)

[x] I plan to open a pull request for this

**Comment by laysauchoa** [comment]
Would be possible to open a separate PR for each of those topics? It makes sense for the review process. Thanks!

**Comment by harshini-rangaswamy** [comment]
I checked with @FloorD and will pick these articles to be migrated.

**Comment by laysauchoa** [comment]
Fixed here: https://github.com/aiven/devportal/pull/1566/
