### ISSUE TITLE
Migrate article: Aiven support details

### ISSUE THREAD

**Issue by lornajane** [aiven/devportal#797]
Migrate the content from this article to fit the documentation portal format https://help.aiven.io/en/articles/868101

(Assign this issue to yourself before you start, and remember to mention the issue number when you open your pull request)

**Comment by encima** [comment]
Support page has been put on the main site: https://aiven.io/support-services  now so maybe we do not need this?

**Comment by KevinBrolly** [comment]
I believe this one can be closed as we no longer need https://help.aiven.io/en/articles/868101 and the https://aiven.io/support-services will suffice, the article currently redirects to there.
