### ISSUE TITLE
Migrate article: Accounts, Teams, Members and Roles

### ISSUE THREAD

**Issue by lornajane** [aiven/devportal#798]
Migrate the content from this article to fit the documentation portal format https://help.aiven.io/en/articles/4206498

(Assign this issue to yourself before you start, and remember to mention the issue number when you open your pull request)

**Comment by FloorD** [comment]
@lornajane solved this one: https://developer.aiven.io/docs/platform/concepts/projects_accounts_access.html

**Comment by lornajane** [comment]
Fixed in #186
