### ISSUE TITLE
Migrate article: Static IP addresses

### ISSUE THREAD

**Issue by lornajane** [aiven/devportal#804]
Migrate the content from this article to fit the documentation portal format https://help.aiven.io/en/articles/5538233

(Assign this issue to yourself before you start, and remember to mention the issue number when you open your pull request)

**Comment by FloorD** [comment]
https://developer.aiven.io/docs/platform/concepts/static-ips.html
https://developer.aiven.io/docs/platform/howto/static-ip-addresses.html

Solved already.
