### ISSUE TITLE
Migrate article: Account Management in Console

### ISSUE THREAD

**Issue by lornajane** [aiven/devportal#805]
Migrate the content from this article to fit the documentation portal format https://help.aiven.io/en/articles/3504926

(Assign this issue to yourself before you start, and remember to mention the issue number when you open your pull request)

**Comment by dragonlancewu** [comment]
@lornajane I plan to work on migrating this article, should it go under https://developer.aiven.io/docs/platform/howto.html?

**Comment by encima** [comment]
@dragonlancewu Yes, that seems like the best place for it. Thank you!

**Comment by staceysalamon-aiven** [comment]
Hey @dewan-ahmed 👋  I am working on updates to our articles for an upcoming release and can take this issue as I plan to repurpose this content in a few places.

**Comment by dewan-ahmed** [comment]
Hi @staceysalamon-aiven for sure, thanks for taking this on. Happy to review once it's ready from your end.

**Comment by staceysalamon-aiven** [comment]
Resolved via #1533
