### ISSUE TITLE
Migrate article: Aiven customer notice: AWS us-east-1 outage on 2017-02-28

### ISSUE THREAD

**Issue by lornajane** [aiven/devportal#806]
Migrate the content from this article to fit the documentation portal format https://help.aiven.io/en/articles/502238

(Assign this issue to yourself before you start, and remember to mention the issue number when you open your pull request)

**Comment by encima** [comment]
Is this worth closing as there is probably no need to migrate something from 5 years ago when future content would be at status.aiven.io?

**Comment by lornajane** [comment]
This is a good spot! I think this content would go on the blog these days too. Closing as you suggest.
