### ISSUE TITLE
Migrate article: Setting up SAML authentication with Google G-Suite

### ISSUE THREAD

**Issue by lornajane** [aiven/devportal#807]
Migrate the content from this article to fit the documentation portal format https://help.aiven.io/en/articles/3447699

(Assign this issue to yourself before you start, and remember to mention the issue number when you open your pull request)

**Comment by cr-aiven** [comment]
@FloorD Do we want to update the of the help page to reflect Googles migration away from GSuite to Google Workspace? As I understand it there is no functional difference between SAML for either one but there are definitely branding/presentation pages between them.

**Comment by dewan-ahmed** [comment]
Hi @lornajane @FloorD bumping this issue up which is part of a high-priority epic. @cr-aiven is awaiting your response.

**Comment by lornajane** [comment]
Could someone with knowledge of the SAML space help here please? @encima or @ftisiot, would you be able to chime in on what updates would be appropriate for the Google article?

**Comment by dewan-ahmed** [comment]
Also tagging @runwuf who'll be working on [another SAML-related issue](https://github.com/aiven/devportal/issues/812).

**Comment by runwuf** [comment]
Thanks for tagging me @dewan-ahmed!
I have recently gone through all the steps in this original help article, the steps are correct, the screenshots needs to be updated.  There are gotchas that would hit errors if you test saml login from Google GSuite/workspace I feel those should be added to the new document. 
@cr-aiven when please continue with the article migration with updated screenshots, I will review it once it's ready.  Thanks!

**Comment by dewan-ahmed** [comment]
Thanks @runwuf ; much appreciated.

**Comment by cr-aiven** [comment]
@runwuf I pushed a change to the branch that fixes the URL overrun length and updated references to GSuite to include Google Workspace, but I can't update the screenshoots because I don't have a domain to use with GSuite/Google Workspace. 
With the exception of the images, the article looks good to me.

**Comment by runwuf** [comment]
@cr-aiven As per our discussion please test out the instructions and capture screenshots using an appropriate domain, ping me if there's issues.  Please also link your PR here when it's ready to be reviewed.  Thanks!

**Comment by cr-aiven** [comment]
@runwuf @lornajane I've spoken with both of you separately about this issue but wanted to record the final verdict here.
Google Workspace is different enough to warrant it's own how-to article so I'm creating an issue and linking it under https://github.com/aiven/devportal/issues/816

**Comment by staceysalamon-aiven** [comment]
Closing as another issue was opened and new functionality will soon be added that changes how this works anyway.
