### ISSUE TITLE
Migrate article: Attach VPC to AWS Transit Gateway

### ISSUE THREAD

**Issue by lornajane** [aiven/devportal#808]
Migrate the content from this article to fit the documentation portal format https://help.aiven.io/en/articles/3507710

(Assign this issue to yourself before you start, and remember to mention the issue number when you open your pull request)

**Comment by dewan-ahmed** [comment]
From the existing article:

> Note that cross-region attachments are not currently supported by TGW.

From [AWS documentation](https://aws.amazon.com/blogs/networking-and-content-delivery/building-a-global-network-using-aws-transit-gateway-inter-region-peering/#:~:text=At%20re%3AInvent%202019%20we,deployed%20in%20other%20AWS%20Regions.):

> At re:Invent 2019 we [announced that AWS Transit Gateway now supports inter-Region peering](https://youtu.be/xLbx-iqjZxk?t=1797). This means that all the Amazon VPCs, Site-to-Site VPN connections, and Direct Connect gateways attached to an AWS Transit Gateway hosted in one AWS Region can exchange traffic with resources deployed in other AWS Regions.

Looking to validate this and get suggestion on possible edits to the existing article from an SA colleague.

**Comment by dewan-ahmed** [comment]
> The Aiven AWS account ID is 675999398324.

Is this ID static and Ok to be on public docs?
