### ISSUE TITLE
Migrate article: Setting up SAML authentication with Okta

### ISSUE THREAD

**Issue by lornajane** [aiven/devportal#812]
Migrate the content from this article to fit the documentation portal format https://help.aiven.io/en/articles/3438800

(Assign this issue to yourself before you start, and remember to mention the issue number when you open your pull request)

**Comment by runwuf** [comment]
I'm working on this one.  All the steps have been tested with new screenshots captures, expect a PR on Monday, Aug 29th.

**Comment by runwuf** [comment]
https://github.com/aiven/devportal/pull/1321
