### ISSUE TITLE
Migrate article: SAML Authentication

### ISSUE THREAD

**Issue by lornajane** [aiven/devportal#813]
Migrate the content from this article to fit the documentation portal format https://help.aiven.io/en/articles/3376377

(Assign this issue to yourself before you start, and remember to mention the issue number when you open your pull request)

**Comment by encima** [comment]
Related Issues (subsets of this article):
#811 
#824 
#825 
#812 
#810 

It might be worth discussing the methodology for migrating these, for example:
1. Migrate all as they are and review later
2. Combine into a single article with a split for the differences
3. Have one "root" article with links to children (or text imported from the children)

**Comment by ftisiot** [comment]
Close as it's solved in https://github.com/aiven/devportal/pull/1206
