### ISSUE TITLE
Migrate article: Using AWS PrivateLink with Aiven services

### ISSUE THREAD

**Issue by lornajane** [aiven/devportal#814]
Migrate the content from this article to fit the documentation portal format https://help.aiven.io/en/articles/4820209

(Assign this issue to yourself before you start, and remember to mention the issue number when you open your pull request)

**Comment by dewan-ahmed** [comment]
Unless there's an SA planning to work on this, I can take this on since this is part of the high-priority articles Epic (to be completed by this month).
