### ISSUE TITLE
Migrate article: Alternatives to Setting Up IdP Initiated SSO

### ISSUE THREAD

**Issue by lornajane** [aiven/devportal#815]
Migrate the content from this article to fit the documentation portal format https://help.aiven.io/en/articles/4386696

(Assign this issue to yourself before you start, and remember to mention the issue number when you open your pull request)

**Comment by dewan-ahmed** [comment]
Unless there's an SA planning to work on this, I can take this on since this is part of the high-priority articles Epic (to be completed by this month).

**Comment by lornajane** [comment]
I doubt either @encima or @ak-aiven will mind having help! If you have the knowledge on the topic then go for it!

**Comment by dewan-ahmed** [comment]
Thanks @lornajane 

Hi @encima @ak-aiven I see the following line on the original article:

> When the feature has been released, we will remove this article but please contact us if you would like to be alerted when this is available.

Is this feature already released or soon-to-be-released? I wanted to be aware of that when migrating the article. If it's Ok, I'll add one of you as a reviewer. Thank you.

**Comment by encima** [comment]
This feature is released and available for any SAML setup. We can close this and remove the original too

**Comment by dewan-ahmed** [comment]
Thanks @encima 
@lornajane a note that the original help article needs to be retired. Thanks.

**Comment by lornajane** [comment]
Would it make sense to redirect to another page? Please open this additional follow-up action as a new issue, it may get lost as a note

**Comment by dewan-ahmed** [comment]
> Would it make sense to redirect to another page?

I assume the above is a question to @encima 

I created https://github.com/aiven/devportal/issues/1320 for the retirement task of https://help.aiven.io/en/articles/4386696.

**Comment by encima** [comment]
> Would it make sense to redirect to another page? Please open this additional follow-up action as a new issue, it may get lost as a note

Linking reply here:
https://github.com/aiven/devportal/issues/1320#issuecomment-1230867380

But yes, we could redirect to the SAML setup guide instead
