### ISSUE TITLE
Migrate article: Migrate Public Service to VPC

### ISSUE THREAD

**Issue by lornajane** [aiven/devportal#820]
Migrate the content from this article to fit the documentation portal format https://help.aiven.io/en/articles/5408586

(Assign this issue to yourself before you start, and remember to mention the issue number when you open your pull request)

**Comment by dewan-ahmed** [comment]
Hi @encima are you planning to work on this soon? I can take this on since this is part of the high-priority articles Epic (to be completed by this month). Thanks.

**Comment by encima** [comment]
I have been away so I will work on this maybe Tuesday at the earliest. Feel free to take it if you like!

**Comment by dewan-ahmed** [comment]
No worries @encima 
Tuesday/Wednesday sounds good.
