### ISSUE TITLE
Migrate article: Setting up SAML with Centrify

### ISSUE THREAD

**Issue by lornajane** [aiven/devportal#824]
Migrate the content from this article to fit the documentation portal format https://help.aiven.io/en/articles/4485814

(Assign this issue to yourself before you start, and remember to mention the issue number when you open your pull request)

**Comment by FloorD** [comment]
Thycotic and Centrify are now Delinea. Should I create new docs for this, @lornajane ?

**Comment by lornajane** [comment]
I'm actually not familiar with these tools, but if centrify has rebranded then let's pick that up with whatever their docs are using today?

**Comment by encima** [comment]
@FloorD are you working on this? I am assuming we would need to create a demo account with Delinea and it might be worth adding those credentials to our internal credential manager

**Comment by encima** [comment]
Under Delinea, it is much harder to get a trial and their tools have been combined so they do not have a specific IdP but a cloud account lifecycle manager. I would propose that we remove this article, close the issue and create one if there is demand. Do you have thoughts, @lornajane @FloorD ?

**Comment by lornajane** [comment]
I'd be content to remove it if you think it's less useful than it was. Could you nominate a place to redirect the old article to though, is there a generic SAML page that would work?

**Comment by encima** [comment]
there is indeed @dewan-ahmed would you mind adding the same redirect for this article to the spreadsheet as you did in the previous issue (sorry, I do not know the sheet to use!)

**Comment by dewan-ahmed** [comment]
Existing article https://docs.aiven.io/docs/platform/howto/list-saml.html will be used to point to this Help article. 

@lornajane I've added the following to the content migration spreadsheet:

1. Under "Content on number of views" sheet, "Article migrated: N" with comment.
2. Under "Platform" sheet, added "https://help.aiven.io/en/articles/4485814-setting-up-saml-with-centrify" pointing to "https://docs.aiven.io/docs/platform/howto/list-saml.html" with comment. 

Please confirm these steps. I assume there will be an SRE ticket for the redirection. Thanks.
