### ISSUE TITLE
Migrate article: Handling Postgresql node replacements when using Debezium for Change Data Capture

### ISSUE THREAD

**Issue by lornajane** [aiven/devportal#827]
Migrate the content from this article to fit the documentation portal format https://help.aiven.io/en/articles/5424203

(Assign this issue to yourself before you start, and remember to mention the issue number when you open your pull request)

**Comment by zhangmmaiven** [comment]
![image](https://user-images.githubusercontent.com/113997791/192988302-155c58f9-43b2-4f81-809e-2ddc15f16b17.png)
make spell throws error to this kind of spelling. It was supposed to be org.postgresql.util... but I change it to org.PostgreSQL.util to make the spell check pass. 

I think the rule should be modified.

**Comment by ftisiot** [comment]
I'll review that later one. keep the lowercase on that for now

**Comment by lornajane** [comment]
This is one of our high priority articles, @zhangmmaiven are you still working on this?

**Comment by zhangmmaiven** [comment]
@lornajane  I was off for a few weeks but this one is merged already, I guess we can close this ticket?
https://github.com/aiven/devportal/pull/1426

**Comment by lornajane** [comment]
Best answer ever :) Thanks!
