### ISSUE TITLE
Header hides the right side container

### ISSUE THREAD

**Issue by zoghlami-khalil** [aiven/devportal#832]
On the main page, https://developer.aiven.io/

When on mobile (or when the browser tab is not fullscreen), the header gets in front of the rightside container **"Contents"** so it is no longer clickable.

<img src="https://user-images.githubusercontent.com/76956031/168444115-998d51d7-c5c9-49d4-9f23-8c8803763c2a.jpg" width="250"> <img src="https://user-images.githubusercontent.com/76956031/168444095-874bbfe8-1128-42b7-b1ca-51991421cfd6.jpg" width="250"> <img src="https://user-images.githubusercontent.com/76956031/168444100-d0e374a7-5c36-4836-81c1-0402a0deb09e.jpg" width="250">
<img src="https://user-images.githubusercontent.com/76956031/168444104-1bd1f4ad-116e-451e-bd5d-92079415a6e0.JPG">

**Comment by lornajane** [comment]
This seems better since the recent UI refresh, so I'll close this issue but please let us know if you still see a problem here.
