### ISSUE TITLE
Duplicate link

### ISSUE THREAD

**Issue by TibsAtWork** [aiven/devportal#839]
# What's wrong?

If I `cd` into the `deportal` directory, and run the following commands:
```
make clean
make html
```
I see an error saying
```
<home>/sw/aiven/devportal/docs/products/mysql/howto/connect-from-cli.rst:61: WARNING: Duplicate explicit target name: "mysql documentation".
```
(where `<home>` will be replaced by your home directory).

If you look in the file `docs/products/mysql/howto/connect-from-cli.rst` and search for "`mysql documentation`", you will find two links with the same name but different targets:

```
`MySQL documentation <https://dev.mysql.com/doc/mysql-shell/8.0/en/mysql-shell-install.html>_`
```
and
```
`MySQL documentation <https://dev.mysql.com/doc/refman/8.0/en/mysql.html>_`
```

It should be possible to fix this issue by adding another underscore (`_`) to the end of each link - that is, so they both end in `>__` instead of `>_`.

**Comment by laysauchoa** [comment]
This is no longer an issue in ``main``
