### ISSUE TITLE
JDBC sink connector documentation references OpenSearch instead of target database

### ISSUE THREAD

**Issue by ftisiot** [aiven/devportal#848]
# What's wrong?

The [JDBC sink connector documentation](https://developer.aiven.io/docs/products/kafka/kafka-connect/howto/jdbc-sink.html) references:

```
Verify the presence of the data in the target **OpenSearch®** service, the index name is equal to the Apache Kafka topic name
```

It should be a reference to the target database table

# URL of affected page, and any other information

https://developer.aiven.io/docs/products/kafka/kafka-connect/howto/jdbc-sink.html

**Comment by Hemant-Mulchandani** [comment]
Can you please elaborate on the changes required?

**Comment by ftisiot** [comment]
There's a sentence saying 

```
Verify the presence of the data in the target OpenSearch® service, the index name is equal to the Apache Kafka topic name
```

But the target is a database, therefore should be changed to reflect what the output is (a Database and not OpenSearch, and a table instead of an index)

**Comment by laysauchoa** [comment]
Fixed
