### ISSUE TITLE
Terraform Recipe Request - Kafka service with custom configurations

### ISSUE THREAD

**Issue by dewan-ahmed** [aiven/devportal#864]
# What should we add to our content collections?

Create a new Terraform Cookbook Recipe for Kafka with Kafka Connect services with custom configurations

# Suggested instructions for this task

1. Review [Terraform basics](https://www.terraform.io/intro)
2. Review [setting up first Aiven Terraform project](https://developer.aiven.io/docs/tools/terraform/get-started.html)
3. Run the [Terraform code](https://github.com/aiven/aiven-examples/blob/master/terraform/kafka/kafka.tf) to create a Kafka service with custom configuration. Feel free to do some research over specific custom configurations that are being used in the industry.
4. Check out [the existing recipes ](https://developer.aiven.io/docs/tools/terraform/reference/cookbook.html) and create a PR for the new recipe.

**Comment by sluhur** [comment]
https://github.com/aiven/devportal/pull/941
