### ISSUE TITLE
Terraform Recipe Request - Standalone PostgreSQL service within a single cloud and region

### ISSUE THREAD

**Issue by dewan-ahmed** [aiven/devportal#865]
# What should we add to our content collections?

Create a new Terraform Cookbook Recipe for a standalone PostgreSQL service within a single cloud and region

# Suggested instructions for this task

1. Review [Terraform basics](https://www.terraform.io/intro)
2. Review [setting up first Aiven Terraform project](https://developer.aiven.io/docs/tools/terraform/get-started.html)
3. Run the [Terraform code](https://registry.terraform.io/providers/aiven/aiven/latest/docs/resources/pg) to create a standalone PostgreSQL service within a single cloud and region and ensure you can see the service running on Aiven platform. Do some research on why [static IPs](https://registry.terraform.io/providers/aiven/aiven/latest/docs/resources/static_ip) are needed and include that finding on the recipe.
4. Check out [the existing recipes ](https://developer.aiven.io/docs/tools/terraform/reference/cookbook.html) and create a PR for the new recipe.

**Comment by sluhur** [comment]
I tried creating the terraform without static ip and it is successful. But then when I open the service, there is additional option Access Route (Dynamic - Public) which I don't see on the normal service creation.

However when I tried to include static ip, it's giving me error Reference to undeclared resource.  A managed resource "aiven_static_ip" "ips" has not been declared in the root module. What IP address should I declare?

**Comment by dewan-ahmed** [comment]
Hi @sluhur thanks for taking on this recipe. For static IP, you have to declare this Aiven Terraform resource: https://registry.terraform.io/providers/aiven/aiven/latest/docs/resources/static_ip

But using static IP is not needed in this example. Feel free to check out the other PG example where static IP is not used: https://developer.aiven.io/docs/tools/terraform/reference/cookbook/multicloud-postgresql-recipe.html

Thanks again and looking forward to your contributions.

**Comment by dewan-ahmed** [comment]
Hi @sluhur please let me know if you have any questions or need any help. Thanks.

**Comment by dewan-ahmed** [comment]
Resolved via https://github.com/aiven/devportal/pull/925
