### ISSUE TITLE
some misplace words here

### ISSUE THREAD

**Issue by laysauchoa** [aiven/devportal#888]
Some wrong display of information on this page which I do not know why

# Where would you expect to find this information?
https://developer.aiven.io/docs/tools/api/examples.html
<img width="1920" alt="Screenshot 2022-05-29 at 20 24 47" src="https://user-images.githubusercontent.com/36624597/171007741-9983562c-ae2e-46ac-a263-983ff296e23b.png">

**Comment by Hemant-Mulchandani** [comment]
Hey, can you please help me locate the html file location of this page to fix the issue.
Thanks!
