### ISSUE TITLE
Search should show best articles from either platform

### ISSUE THREAD

**Issue by lornajane** [aiven/devportal#895]
# What's wrong?

The search results show ALL devportal articles, no matter how low their relevance, before ANY help center article (that might well be exactly what is needed). We should _prefer_ devportal articles since they should be more up to date and longer-lived, but if the correct content exists, it should be shown on page 1.

The Search function uses a weighting that's set at index time; I think we need to handle this differently

**Comment by ak-aiven** [comment]
https://github.com/aiven/devportal/pull/1385
