### ISSUE TITLE
OpenSearch benchmarks with a large number of shards

### ISSUE THREAD

**Issue by anelook** [aiven/devportal#898]
# What should we add to our content collections?

In the migrated help article https://help.aiven.io/en/articles/2413410-number-of-shards-and-indexes-in-elasticsearch we have benchmarks. These benchmarks are outdated and need to be re-run and documented.

> Having a large number of shards affect your OpenSearch performance
> out from OpenSearch. Some benchmark results from three-node Aiven
> OpenSearch ``business-8`` cluster:
> 
> -  1 000 shards: no visible effect in OpenSearch performance.
> 
> -  10 000 shards is already quite a lot - creating new shards starts to
>    take longer and longer time. Variance in performance grows.
> 
> -  15 000 shards: creating new shards takes significantly longer time,
>    often tens of seconds.
> 
> -  20 000 shards: inserting new data randomly takes significantly longer
>    times (20x longer than mean). Similarly, variance in search
>    performance grows significantly.
> 
> Aiven for OpenSearch takes a snapshot once every hour. With 10 000 shards
> cluster is continuously taking new backups and deleting old backups from
> backup storage. This will naturally affect service performance, as part
> of the capacity is continuously in use for managing backups.

# Is this something you would work on yourself?

[ ] I plan to open a pull request for this

**Comment by lornajane** [comment]
I think the benchmark data is so easily outdated that we should look at publishing this in blog posts rather than our evergreen docs. It's a great idea, but it shouldn't be an open issue on this repo.
