### ISSUE TITLE
sphinxcontrib-mermaid broken on Sphinx >= 4.0

### ISSUE THREAD

**Issue by jonatasbaldin** [aiven/devportal#9]
Hi there!

sphinxcontrib-mermaid is currently broken for Sphinx >= 4.0, [here is the PR fixing it](https://github.com/mgaitan/sphinxcontrib-mermaid/pull/71).

For now, trying to run `make livehtml` returns the following error:
```bash
Extension error:
Could not import extension sphinxcontrib.mermaid (exception: cannot import name 'ENOENT' from 'sphinx.util.osutil' (/Users/jonatasbaldin/aiven/devportal/venv/lib/python3.8/site-packages/sphinx/util/osutil.py))
Command exited with exit code: 2
The server will continue serving the build folder, but the contents being served are no longer in sync with the documentation sources. Please fix the cause of the error above or press Ctrl+C to stop the server.
```

And I got `404` on the index page on the live server,

Disabling out the `sphinxcontrib.mermaid` from `conf.py:extensions` fixes the issue temporarily.

We have a couple of options:
1. Disable it for now until the PR is merged.
2. Use an earlier version of Sphinx.

What do you think?

**Comment by lornajane** [comment]
I think we should have pinned all the versions of all the libs anyway. Lets get sphinx with < v4.0 and see how that goes?
