### ISSUE TITLE
Update `site-preview.png` image

### ISSUE THREAD

**Issue by ftisiot** [aiven/devportal#910]
# What should we add to our content collections?

(more information is useful here! Were you trying to do something particular?)

The `site-preview.png` (under `/_static/images`) image shown when including devportal content is a bit old, would be good to have a new site preview

# Is this something you would work on yourself?

[ ] I plan to open a pull request for this

**Comment by rahulkarda** [comment]
What about a full page site preview? I'll submit a PR
