### ISSUE TITLE
Replace logo image if needed it

### ISSUE THREAD

**Issue by laysauchoa** [aiven/devportal#913]
Aiven will support and celebrate pride month for the next 11 months as you can fin here: https://aiven.io/blog/celebrating-our-colorful-cast 

The images were replaced in this PR: https://github.com/aiven/devportal/pull/909 

This issue should be revisited in a year (June 2023) to check if the images should be replaced back or not.

**Comment by laysauchoa** [comment]
The logo for the tab will not be changed for the Aiven websites including devprotal

**Comment by ftisiot** [comment]
Want to mention here, that we might also need to change the `site-preview.png` file once we go back to the original image.
I'm now merging https://github.com/aiven/devportal/pull/922 with the updated logo for preview
