### ISSUE TITLE
Reorganise Platform HowTos

### ISSUE THREAD

**Issue by ftisiot** [aiven/devportal#915]
# What should we add to our content collections?

(more information is useful here! Were you trying to do something particular?)

Currently the platform HowTo contains a plain list of all the articles that fill in this folder. But the list is getting longer and articles are not organised or ordered by any particular topic.

We should divide the HowTo into subsections for specific topics, like what has been done for PostgreSQL or Kafka

![list of articles in the platform->howto](https://user-images.githubusercontent.com/11272743/172592762-0b49371b-ab65-4631-830a-ba9d6a517819.png)

# Is this something you would work on yourself?

[ ] I plan to open a pull request for this

**Comment by lornajane** [comment]
Yes please, let's think about the audiences that might use these sets of tasks, and organise along these lines

**Comment by laysauchoa** [comment]
Related to this: https://github.com/aiven/devportal/pull/877

We will have Disable user, Reset user 2FA, Set it up 2FA etc.

**Comment by ftisiot** [comment]
My current idea to split the content is the following:
* User/access management
 * Change email
 * Enable Aiven password
 * Create an auth token
 * Disable 2FA settings
* Service management
 * Create/Fork/Scale/Migrate a service
 * Pause or terminate
 * Tag
 * add storage
* Network tasks
 * VPC 
 * Manage Private IP
 * Handle erros in IP addresses
 * Restrict access to your service
* Monitoring management
 * monitoring services  
 * metrics limit settings for Datadog
 * Prometeus with Aiven

**Comment by rahulkarda** [comment]
> My current idea to split the content is the following:
> 
> * User/access management
>   
>   * Change email
>   * Enable Aiven password
>   * Create an auth token
>   * Disable 2FA settings
> * Service management
>   
>   * Create/Fork/Scale/Migrate a service
>   * Pause or terminate
>   * Tag
>   * add storage
> * Network tasks
>   
>   * VPC
>   * Manage Private IP
>   * Handle erros in IP addresses
>   * Restrict access to your service
> * Monitoring management
>   
>   * monitoring services
>   * metrics limit settings for Datadog
>   * Prometeus with Aiven

I like this approach
