### ISSUE TITLE
Using Terraform/Cron/Lambda etc and tags to schedule powering on/off your services

### ISSUE THREAD

**Issue by encima** [aiven/devportal#933]
# What should we add to our content collections?

Maybe a blog post instead but this would be a cool thing to show with the different tools we have (avn, API, Terraform) and the new tagging functionality. Code samples could go in the https://github.com/aiven/aiven-examples repo

# Is this something you would work on yourself?

[ ] I plan to open a pull request for this

**Comment by lornajane** [comment]
Should be a blog post.
