### ISSUE TITLE
Redis is now ®, not ™

### ISSUE THREAD

**Issue by TibsAtWork** [aiven/devportal#938]
Redis has become a registered mark, rather than just trademarked.

1. Update the vale rule for Redis, and the corresponding tests for the rules
2. Replace all of the occurrences of `Redis™*` with `Redis®*`
3. Update the footer text acknowledging registration marks to say that `*Redis is a registered trademark of Redis Ltd. and the Redis box logo is a mark of Redis Ltd. Any rights therein are reserved to Redis Ltd.` (I think this just needs insertion of the word `registered` into the existing text).

**Comment by laysauchoa** [comment]
Would be possible to help me to link the official information about this, @TibsAtWork?

**Comment by TibsAtWork** [comment]
Apologies - I should have done that earlier. Thanks for pointing this out.

https://redis.io/docs/about/trademark/ is the relevant page at redis.io

The section on "General Use Information" (section 6) is most relevant here - it clarifies that we should be using `®*` (in clause i) and what the acknowledgement text should be (in clause ii)
